// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orderwrite/v1/orderwrite.proto

// Package orderwrite.v1 defines the order-service write-model gRPC contract
// used by order-saga-service.

package orderwritev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderWriteService_CreateDraftOrder_FullMethodName        = "/orderwrite.v1.OrderWriteService/CreateDraftOrder"
	OrderWriteService_SaveRequirementAnswers_FullMethodName  = "/orderwrite.v1.OrderWriteService/SaveRequirementAnswers"
	OrderWriteService_SaveBuyerInitialMessage_FullMethodName = "/orderwrite.v1.OrderWriteService/SaveBuyerInitialMessage"
	OrderWriteService_AttachFileToOrder_FullMethodName       = "/orderwrite.v1.OrderWriteService/AttachFileToOrder"
	OrderWriteService_GetOrderPaymentSnapshot_FullMethodName = "/orderwrite.v1.OrderWriteService/GetOrderPaymentSnapshot"
	OrderWriteService_MarkPaymentPending_FullMethodName      = "/orderwrite.v1.OrderWriteService/MarkPaymentPending"
	OrderWriteService_MarkOrderFunded_FullMethodName         = "/orderwrite.v1.OrderWriteService/MarkOrderFunded"
	OrderWriteService_MarkPaymentFailed_FullMethodName       = "/orderwrite.v1.OrderWriteService/MarkPaymentFailed"
)

// OrderWriteServiceClient is the client API for OrderWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderWriteService owns the authoritative order persistence boundary.
type OrderWriteServiceClient interface {
	CreateDraftOrder(ctx context.Context, in *CreateDraftOrderRequest, opts ...grpc.CallOption) (*CreateDraftOrderResponse, error)
	SaveRequirementAnswers(ctx context.Context, in *SaveRequirementAnswersRequest, opts ...grpc.CallOption) (*SaveRequirementAnswersResponse, error)
	SaveBuyerInitialMessage(ctx context.Context, in *SaveBuyerInitialMessageRequest, opts ...grpc.CallOption) (*SaveBuyerInitialMessageResponse, error)
	AttachFileToOrder(ctx context.Context, in *AttachFileToOrderRequest, opts ...grpc.CallOption) (*AttachFileToOrderResponse, error)
	GetOrderPaymentSnapshot(ctx context.Context, in *GetOrderPaymentSnapshotRequest, opts ...grpc.CallOption) (*GetOrderPaymentSnapshotResponse, error)
	MarkPaymentPending(ctx context.Context, in *MarkPaymentPendingRequest, opts ...grpc.CallOption) (*MarkPaymentPendingResponse, error)
	MarkOrderFunded(ctx context.Context, in *MarkOrderFundedRequest, opts ...grpc.CallOption) (*MarkOrderFundedResponse, error)
	MarkPaymentFailed(ctx context.Context, in *MarkPaymentFailedRequest, opts ...grpc.CallOption) (*MarkPaymentFailedResponse, error)
}

type orderWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderWriteServiceClient(cc grpc.ClientConnInterface) OrderWriteServiceClient {
	return &orderWriteServiceClient{cc}
}

func (c *orderWriteServiceClient) CreateDraftOrder(ctx context.Context, in *CreateDraftOrderRequest, opts ...grpc.CallOption) (*CreateDraftOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDraftOrderResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_CreateDraftOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) SaveRequirementAnswers(ctx context.Context, in *SaveRequirementAnswersRequest, opts ...grpc.CallOption) (*SaveRequirementAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRequirementAnswersResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_SaveRequirementAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) SaveBuyerInitialMessage(ctx context.Context, in *SaveBuyerInitialMessageRequest, opts ...grpc.CallOption) (*SaveBuyerInitialMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveBuyerInitialMessageResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_SaveBuyerInitialMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) AttachFileToOrder(ctx context.Context, in *AttachFileToOrderRequest, opts ...grpc.CallOption) (*AttachFileToOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachFileToOrderResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_AttachFileToOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) GetOrderPaymentSnapshot(ctx context.Context, in *GetOrderPaymentSnapshotRequest, opts ...grpc.CallOption) (*GetOrderPaymentSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderPaymentSnapshotResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_GetOrderPaymentSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) MarkPaymentPending(ctx context.Context, in *MarkPaymentPendingRequest, opts ...grpc.CallOption) (*MarkPaymentPendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkPaymentPendingResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_MarkPaymentPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) MarkOrderFunded(ctx context.Context, in *MarkOrderFundedRequest, opts ...grpc.CallOption) (*MarkOrderFundedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkOrderFundedResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_MarkOrderFunded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderWriteServiceClient) MarkPaymentFailed(ctx context.Context, in *MarkPaymentFailedRequest, opts ...grpc.CallOption) (*MarkPaymentFailedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkPaymentFailedResponse)
	err := c.cc.Invoke(ctx, OrderWriteService_MarkPaymentFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderWriteServiceServer is the server API for OrderWriteService service.
// All implementations should embed UnimplementedOrderWriteServiceServer
// for forward compatibility.
//
// OrderWriteService owns the authoritative order persistence boundary.
type OrderWriteServiceServer interface {
	CreateDraftOrder(context.Context, *CreateDraftOrderRequest) (*CreateDraftOrderResponse, error)
	SaveRequirementAnswers(context.Context, *SaveRequirementAnswersRequest) (*SaveRequirementAnswersResponse, error)
	SaveBuyerInitialMessage(context.Context, *SaveBuyerInitialMessageRequest) (*SaveBuyerInitialMessageResponse, error)
	AttachFileToOrder(context.Context, *AttachFileToOrderRequest) (*AttachFileToOrderResponse, error)
	GetOrderPaymentSnapshot(context.Context, *GetOrderPaymentSnapshotRequest) (*GetOrderPaymentSnapshotResponse, error)
	MarkPaymentPending(context.Context, *MarkPaymentPendingRequest) (*MarkPaymentPendingResponse, error)
	MarkOrderFunded(context.Context, *MarkOrderFundedRequest) (*MarkOrderFundedResponse, error)
	MarkPaymentFailed(context.Context, *MarkPaymentFailedRequest) (*MarkPaymentFailedResponse, error)
}

// UnimplementedOrderWriteServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderWriteServiceServer struct{}

func (UnimplementedOrderWriteServiceServer) CreateDraftOrder(context.Context, *CreateDraftOrderRequest) (*CreateDraftOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDraftOrder not implemented")
}
func (UnimplementedOrderWriteServiceServer) SaveRequirementAnswers(context.Context, *SaveRequirementAnswersRequest) (*SaveRequirementAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRequirementAnswers not implemented")
}
func (UnimplementedOrderWriteServiceServer) SaveBuyerInitialMessage(context.Context, *SaveBuyerInitialMessageRequest) (*SaveBuyerInitialMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBuyerInitialMessage not implemented")
}
func (UnimplementedOrderWriteServiceServer) AttachFileToOrder(context.Context, *AttachFileToOrderRequest) (*AttachFileToOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachFileToOrder not implemented")
}
func (UnimplementedOrderWriteServiceServer) GetOrderPaymentSnapshot(context.Context, *GetOrderPaymentSnapshotRequest) (*GetOrderPaymentSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderPaymentSnapshot not implemented")
}
func (UnimplementedOrderWriteServiceServer) MarkPaymentPending(context.Context, *MarkPaymentPendingRequest) (*MarkPaymentPendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkPaymentPending not implemented")
}
func (UnimplementedOrderWriteServiceServer) MarkOrderFunded(context.Context, *MarkOrderFundedRequest) (*MarkOrderFundedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkOrderFunded not implemented")
}
func (UnimplementedOrderWriteServiceServer) MarkPaymentFailed(context.Context, *MarkPaymentFailedRequest) (*MarkPaymentFailedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkPaymentFailed not implemented")
}
func (UnimplementedOrderWriteServiceServer) testEmbeddedByValue() {}

// UnsafeOrderWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderWriteServiceServer will
// result in compilation errors.
type UnsafeOrderWriteServiceServer interface {
	mustEmbedUnimplementedOrderWriteServiceServer()
}

func RegisterOrderWriteServiceServer(s grpc.ServiceRegistrar, srv OrderWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderWriteService_ServiceDesc, srv)
}

func _OrderWriteService_CreateDraftOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDraftOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).CreateDraftOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_CreateDraftOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).CreateDraftOrder(ctx, req.(*CreateDraftOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_SaveRequirementAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequirementAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).SaveRequirementAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_SaveRequirementAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).SaveRequirementAnswers(ctx, req.(*SaveRequirementAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_SaveBuyerInitialMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBuyerInitialMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).SaveBuyerInitialMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_SaveBuyerInitialMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).SaveBuyerInitialMessage(ctx, req.(*SaveBuyerInitialMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_AttachFileToOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachFileToOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).AttachFileToOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_AttachFileToOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).AttachFileToOrder(ctx, req.(*AttachFileToOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_GetOrderPaymentSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPaymentSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).GetOrderPaymentSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_GetOrderPaymentSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).GetOrderPaymentSnapshot(ctx, req.(*GetOrderPaymentSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_MarkPaymentPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkPaymentPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).MarkPaymentPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_MarkPaymentPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).MarkPaymentPending(ctx, req.(*MarkPaymentPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_MarkOrderFunded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkOrderFundedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).MarkOrderFunded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_MarkOrderFunded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).MarkOrderFunded(ctx, req.(*MarkOrderFundedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderWriteService_MarkPaymentFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkPaymentFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderWriteServiceServer).MarkPaymentFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderWriteService_MarkPaymentFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderWriteServiceServer).MarkPaymentFailed(ctx, req.(*MarkPaymentFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderWriteService_ServiceDesc is the grpc.ServiceDesc for OrderWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderwrite.v1.OrderWriteService",
	HandlerType: (*OrderWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDraftOrder",
			Handler:    _OrderWriteService_CreateDraftOrder_Handler,
		},
		{
			MethodName: "SaveRequirementAnswers",
			Handler:    _OrderWriteService_SaveRequirementAnswers_Handler,
		},
		{
			MethodName: "SaveBuyerInitialMessage",
			Handler:    _OrderWriteService_SaveBuyerInitialMessage_Handler,
		},
		{
			MethodName: "AttachFileToOrder",
			Handler:    _OrderWriteService_AttachFileToOrder_Handler,
		},
		{
			MethodName: "GetOrderPaymentSnapshot",
			Handler:    _OrderWriteService_GetOrderPaymentSnapshot_Handler,
		},
		{
			MethodName: "MarkPaymentPending",
			Handler:    _OrderWriteService_MarkPaymentPending_Handler,
		},
		{
			MethodName: "MarkOrderFunded",
			Handler:    _OrderWriteService_MarkOrderFunded_Handler,
		},
		{
			MethodName: "MarkPaymentFailed",
			Handler:    _OrderWriteService_MarkPaymentFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderwrite/v1/orderwrite.proto",
}
