// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orderwrite/v1/orderwrite.proto

// Package orderwrite.v1 defines the order-service write-model gRPC contract
// used by order-saga-service.

package orderwritev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSnapshot struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	OrderId                    string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SagaId                     string                 `protobuf:"bytes,2,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	BuyerUserId                string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId               string                 `protobuf:"bytes,4,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	GigId                      string                 `protobuf:"bytes,5,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	GigTitleSnapshot           string                 `protobuf:"bytes,6,opt,name=gig_title_snapshot,json=gigTitleSnapshot,proto3" json:"gig_title_snapshot,omitempty"`
	PackageId                  string                 `protobuf:"bytes,7,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageTitleSnapshot       string                 `protobuf:"bytes,8,opt,name=package_title_snapshot,json=packageTitleSnapshot,proto3" json:"package_title_snapshot,omitempty"`
	PackageDescriptionSnapshot string                 `protobuf:"bytes,9,opt,name=package_description_snapshot,json=packageDescriptionSnapshot,proto3" json:"package_description_snapshot,omitempty"`
	PriceAmountSnapshot        int64                  `protobuf:"varint,10,opt,name=price_amount_snapshot,json=priceAmountSnapshot,proto3" json:"price_amount_snapshot,omitempty"`
	PriceCurrencySnapshot      string                 `protobuf:"bytes,11,opt,name=price_currency_snapshot,json=priceCurrencySnapshot,proto3" json:"price_currency_snapshot,omitempty"`
	DeliveryDaysSnapshot       int32                  `protobuf:"varint,12,opt,name=delivery_days_snapshot,json=deliveryDaysSnapshot,proto3" json:"delivery_days_snapshot,omitempty"`
	RevisionCountSnapshot      int32                  `protobuf:"varint,13,opt,name=revision_count_snapshot,json=revisionCountSnapshot,proto3" json:"revision_count_snapshot,omitempty"`
	BuyerInitialMessage        string                 `protobuf:"bytes,14,opt,name=buyer_initial_message,json=buyerInitialMessage,proto3" json:"buyer_initial_message,omitempty"`
	Status                     string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	PaymentIntentId            string                 `protobuf:"bytes,16,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	CreatedAt                  string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                  string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FundedAt                   string                 `protobuf:"bytes,19,opt,name=funded_at,json=fundedAt,proto3" json:"funded_at,omitempty"`
	DeliveredAt                string                 `protobuf:"bytes,20,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CompletedAt                string                 `protobuf:"bytes,21,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DisputedAt                 string                 `protobuf:"bytes,22,opt,name=disputed_at,json=disputedAt,proto3" json:"disputed_at,omitempty"`
	RevisionCountUsed          int32                  `protobuf:"varint,23,opt,name=revision_count_used,json=revisionCountUsed,proto3" json:"revision_count_used,omitempty"`
	BuyerResponseDeadline      string                 `protobuf:"bytes,24,opt,name=buyer_response_deadline,json=buyerResponseDeadline,proto3" json:"buyer_response_deadline,omitempty"`
	PaymentReleaseId           string                 `protobuf:"bytes,25,opt,name=payment_release_id,json=paymentReleaseId,proto3" json:"payment_release_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *OrderSnapshot) Reset() {
	*x = OrderSnapshot{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSnapshot) ProtoMessage() {}

func (x *OrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSnapshot.ProtoReflect.Descriptor instead.
func (*OrderSnapshot) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{0}
}

func (x *OrderSnapshot) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderSnapshot) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *OrderSnapshot) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *OrderSnapshot) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *OrderSnapshot) GetGigId() string {
	if x != nil {
		return x.GigId
	}
	return ""
}

func (x *OrderSnapshot) GetGigTitleSnapshot() string {
	if x != nil {
		return x.GigTitleSnapshot
	}
	return ""
}

func (x *OrderSnapshot) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OrderSnapshot) GetPackageTitleSnapshot() string {
	if x != nil {
		return x.PackageTitleSnapshot
	}
	return ""
}

func (x *OrderSnapshot) GetPackageDescriptionSnapshot() string {
	if x != nil {
		return x.PackageDescriptionSnapshot
	}
	return ""
}

func (x *OrderSnapshot) GetPriceAmountSnapshot() int64 {
	if x != nil {
		return x.PriceAmountSnapshot
	}
	return 0
}

func (x *OrderSnapshot) GetPriceCurrencySnapshot() string {
	if x != nil {
		return x.PriceCurrencySnapshot
	}
	return ""
}

func (x *OrderSnapshot) GetDeliveryDaysSnapshot() int32 {
	if x != nil {
		return x.DeliveryDaysSnapshot
	}
	return 0
}

func (x *OrderSnapshot) GetRevisionCountSnapshot() int32 {
	if x != nil {
		return x.RevisionCountSnapshot
	}
	return 0
}

func (x *OrderSnapshot) GetBuyerInitialMessage() string {
	if x != nil {
		return x.BuyerInitialMessage
	}
	return ""
}

func (x *OrderSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderSnapshot) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *OrderSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderSnapshot) GetFundedAt() string {
	if x != nil {
		return x.FundedAt
	}
	return ""
}

func (x *OrderSnapshot) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

func (x *OrderSnapshot) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *OrderSnapshot) GetDisputedAt() string {
	if x != nil {
		return x.DisputedAt
	}
	return ""
}

func (x *OrderSnapshot) GetRevisionCountUsed() int32 {
	if x != nil {
		return x.RevisionCountUsed
	}
	return 0
}

func (x *OrderSnapshot) GetBuyerResponseDeadline() string {
	if x != nil {
		return x.BuyerResponseDeadline
	}
	return ""
}

func (x *OrderSnapshot) GetPaymentReleaseId() string {
	if x != nil {
		return x.PaymentReleaseId
	}
	return ""
}

type OrderQuestionOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQuestionOption) Reset() {
	*x = OrderQuestionOption{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuestionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuestionOption) ProtoMessage() {}

func (x *OrderQuestionOption) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuestionOption.ProtoReflect.Descriptor instead.
func (*OrderQuestionOption) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{1}
}

func (x *OrderQuestionOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OrderQuestionOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type OrderQuestionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Options       []*OrderQuestionOption `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQuestionSnapshot) Reset() {
	*x = OrderQuestionSnapshot{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuestionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuestionSnapshot) ProtoMessage() {}

func (x *OrderQuestionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuestionSnapshot.ProtoReflect.Descriptor instead.
func (*OrderQuestionSnapshot) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{2}
}

func (x *OrderQuestionSnapshot) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *OrderQuestionSnapshot) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OrderQuestionSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderQuestionSnapshot) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *OrderQuestionSnapshot) GetOptions() []*OrderQuestionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OrderQuestionSnapshot) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type OrderAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAnswer) Reset() {
	*x = OrderAnswer{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAnswer) ProtoMessage() {}

func (x *OrderAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAnswer.ProtoReflect.Descriptor instead.
func (*OrderAnswer) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{3}
}

func (x *OrderAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *OrderAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AttachmentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentSnapshot) Reset() {
	*x = AttachmentSnapshot{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentSnapshot) ProtoMessage() {}

func (x *AttachmentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentSnapshot.ProtoReflect.Descriptor instead.
func (*AttachmentSnapshot) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{4}
}

func (x *AttachmentSnapshot) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *AttachmentSnapshot) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *AttachmentSnapshot) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentSnapshot) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AttachmentSnapshot) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AttachmentSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateDraftOrderRequest struct {
	state                      protoimpl.MessageState   `protogen:"open.v1"`
	SagaId                     string                   `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	OrderId                    string                   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId                string                   `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId               string                   `protobuf:"bytes,4,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	GigId                      string                   `protobuf:"bytes,5,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	GigTitleSnapshot           string                   `protobuf:"bytes,6,opt,name=gig_title_snapshot,json=gigTitleSnapshot,proto3" json:"gig_title_snapshot,omitempty"`
	PackageId                  string                   `protobuf:"bytes,7,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageTitleSnapshot       string                   `protobuf:"bytes,8,opt,name=package_title_snapshot,json=packageTitleSnapshot,proto3" json:"package_title_snapshot,omitempty"`
	PackageDescriptionSnapshot string                   `protobuf:"bytes,9,opt,name=package_description_snapshot,json=packageDescriptionSnapshot,proto3" json:"package_description_snapshot,omitempty"`
	PriceAmountSnapshot        int64                    `protobuf:"varint,10,opt,name=price_amount_snapshot,json=priceAmountSnapshot,proto3" json:"price_amount_snapshot,omitempty"`
	PriceCurrencySnapshot      string                   `protobuf:"bytes,11,opt,name=price_currency_snapshot,json=priceCurrencySnapshot,proto3" json:"price_currency_snapshot,omitempty"`
	DeliveryDaysSnapshot       int32                    `protobuf:"varint,12,opt,name=delivery_days_snapshot,json=deliveryDaysSnapshot,proto3" json:"delivery_days_snapshot,omitempty"`
	RevisionCountSnapshot      int32                    `protobuf:"varint,13,opt,name=revision_count_snapshot,json=revisionCountSnapshot,proto3" json:"revision_count_snapshot,omitempty"`
	Questions                  []*OrderQuestionSnapshot `protobuf:"bytes,14,rep,name=questions,proto3" json:"questions,omitempty"`
	IdempotencyKey             string                   `protobuf:"bytes,15,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestedAt                string                   `protobuf:"bytes,16,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateDraftOrderRequest) Reset() {
	*x = CreateDraftOrderRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftOrderRequest) ProtoMessage() {}

func (x *CreateDraftOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateDraftOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDraftOrderRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetGigId() string {
	if x != nil {
		return x.GigId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetGigTitleSnapshot() string {
	if x != nil {
		return x.GigTitleSnapshot
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetPackageTitleSnapshot() string {
	if x != nil {
		return x.PackageTitleSnapshot
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetPackageDescriptionSnapshot() string {
	if x != nil {
		return x.PackageDescriptionSnapshot
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetPriceAmountSnapshot() int64 {
	if x != nil {
		return x.PriceAmountSnapshot
	}
	return 0
}

func (x *CreateDraftOrderRequest) GetPriceCurrencySnapshot() string {
	if x != nil {
		return x.PriceCurrencySnapshot
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetDeliveryDaysSnapshot() int32 {
	if x != nil {
		return x.DeliveryDaysSnapshot
	}
	return 0
}

func (x *CreateDraftOrderRequest) GetRevisionCountSnapshot() int32 {
	if x != nil {
		return x.RevisionCountSnapshot
	}
	return 0
}

func (x *CreateDraftOrderRequest) GetQuestions() []*OrderQuestionSnapshot {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *CreateDraftOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateDraftOrderRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type CreateDraftOrderResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Order         *OrderSnapshot           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Questions     []*OrderQuestionSnapshot `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftOrderResponse) Reset() {
	*x = CreateDraftOrderResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftOrderResponse) ProtoMessage() {}

func (x *CreateDraftOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateDraftOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDraftOrderResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateDraftOrderResponse) GetQuestions() []*OrderQuestionSnapshot {
	if x != nil {
		return x.Questions
	}
	return nil
}

type SaveRequirementAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Answers       []*OrderAnswer         `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequirementAnswersRequest) Reset() {
	*x = SaveRequirementAnswersRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequirementAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequirementAnswersRequest) ProtoMessage() {}

func (x *SaveRequirementAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequirementAnswersRequest.ProtoReflect.Descriptor instead.
func (*SaveRequirementAnswersRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{7}
}

func (x *SaveRequirementAnswersRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SaveRequirementAnswersRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *SaveRequirementAnswersRequest) GetAnswers() []*OrderAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *SaveRequirementAnswersRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type SaveRequirementAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequirementAnswersResponse) Reset() {
	*x = SaveRequirementAnswersResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequirementAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequirementAnswersResponse) ProtoMessage() {}

func (x *SaveRequirementAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequirementAnswersResponse.ProtoReflect.Descriptor instead.
func (*SaveRequirementAnswersResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{8}
}

func (x *SaveRequirementAnswersResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type SaveBuyerInitialMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBuyerInitialMessageRequest) Reset() {
	*x = SaveBuyerInitialMessageRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBuyerInitialMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBuyerInitialMessageRequest) ProtoMessage() {}

func (x *SaveBuyerInitialMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBuyerInitialMessageRequest.ProtoReflect.Descriptor instead.
func (*SaveBuyerInitialMessageRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{9}
}

func (x *SaveBuyerInitialMessageRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SaveBuyerInitialMessageRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *SaveBuyerInitialMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveBuyerInitialMessageRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type SaveBuyerInitialMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBuyerInitialMessageResponse) Reset() {
	*x = SaveBuyerInitialMessageResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBuyerInitialMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBuyerInitialMessageResponse) ProtoMessage() {}

func (x *SaveBuyerInitialMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBuyerInitialMessageResponse.ProtoReflect.Descriptor instead.
func (*SaveBuyerInitialMessageResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{10}
}

func (x *SaveBuyerInitialMessageResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type AttachFileToOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,3,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,8,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFileToOrderRequest) Reset() {
	*x = AttachFileToOrderRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFileToOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFileToOrderRequest) ProtoMessage() {}

func (x *AttachFileToOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFileToOrderRequest.ProtoReflect.Descriptor instead.
func (*AttachFileToOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{11}
}

func (x *AttachFileToOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AttachFileToOrderRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AttachFileToOrderRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type AttachFileToOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Attachment    *AttachmentSnapshot    `protobuf:"bytes,2,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachFileToOrderResponse) Reset() {
	*x = AttachFileToOrderResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachFileToOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFileToOrderResponse) ProtoMessage() {}

func (x *AttachFileToOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFileToOrderResponse.ProtoReflect.Descriptor instead.
func (*AttachFileToOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{12}
}

func (x *AttachFileToOrderResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *AttachFileToOrderResponse) GetAttachment() *AttachmentSnapshot {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type GetOrderPaymentSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPaymentSnapshotRequest) Reset() {
	*x = GetOrderPaymentSnapshotRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPaymentSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPaymentSnapshotRequest) ProtoMessage() {}

func (x *GetOrderPaymentSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPaymentSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetOrderPaymentSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderPaymentSnapshotRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderPaymentSnapshotRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

type GetOrderPaymentSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPaymentSnapshotResponse) Reset() {
	*x = GetOrderPaymentSnapshotResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPaymentSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPaymentSnapshotResponse) ProtoMessage() {}

func (x *GetOrderPaymentSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPaymentSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetOrderPaymentSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderPaymentSnapshotResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkPaymentPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,3,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentPendingRequest) Reset() {
	*x = MarkPaymentPendingRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentPendingRequest) ProtoMessage() {}

func (x *MarkPaymentPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentPendingRequest.ProtoReflect.Descriptor instead.
func (*MarkPaymentPendingRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{15}
}

func (x *MarkPaymentPendingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkPaymentPendingRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MarkPaymentPendingRequest) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *MarkPaymentPendingRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkPaymentPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentPendingResponse) Reset() {
	*x = MarkPaymentPendingResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentPendingResponse) ProtoMessage() {}

func (x *MarkPaymentPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentPendingResponse.ProtoReflect.Descriptor instead.
func (*MarkPaymentPendingResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{16}
}

func (x *MarkPaymentPendingResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkOrderFundedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderFundedRequest) Reset() {
	*x = MarkOrderFundedRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderFundedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderFundedRequest) ProtoMessage() {}

func (x *MarkOrderFundedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderFundedRequest.ProtoReflect.Descriptor instead.
func (*MarkOrderFundedRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{17}
}

func (x *MarkOrderFundedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkOrderFundedRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MarkOrderFundedRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkOrderFundedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderFundedResponse) Reset() {
	*x = MarkOrderFundedResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderFundedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderFundedResponse) ProtoMessage() {}

func (x *MarkOrderFundedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderFundedResponse.ProtoReflect.Descriptor instead.
func (*MarkOrderFundedResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{18}
}

func (x *MarkOrderFundedResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkPaymentFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentFailedRequest) Reset() {
	*x = MarkPaymentFailedRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentFailedRequest) ProtoMessage() {}

func (x *MarkPaymentFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentFailedRequest.ProtoReflect.Descriptor instead.
func (*MarkPaymentFailedRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{19}
}

func (x *MarkPaymentFailedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkPaymentFailedRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MarkPaymentFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MarkPaymentFailedRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkPaymentFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentFailedResponse) Reset() {
	*x = MarkPaymentFailedResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentFailedResponse) ProtoMessage() {}

func (x *MarkPaymentFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentFailedResponse.ProtoReflect.Descriptor instead.
func (*MarkPaymentFailedResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{20}
}

func (x *MarkPaymentFailedResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderLifecycleSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLifecycleSnapshotRequest) Reset() {
	*x = GetOrderLifecycleSnapshotRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLifecycleSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLifecycleSnapshotRequest) ProtoMessage() {}

func (x *GetOrderLifecycleSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLifecycleSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetOrderLifecycleSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{21}
}

func (x *GetOrderLifecycleSnapshotRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderLifecycleSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLifecycleSnapshotResponse) Reset() {
	*x = GetOrderLifecycleSnapshotResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLifecycleSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLifecycleSnapshotResponse) ProtoMessage() {}

func (x *GetOrderLifecycleSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLifecycleSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetOrderLifecycleSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{22}
}

func (x *GetOrderLifecycleSnapshotResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type SaveDeliveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SellerUserId    string                 `protobuf:"bytes,2,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	DeliveryMessage string                 `protobuf:"bytes,3,opt,name=delivery_message,json=deliveryMessage,proto3" json:"delivery_message,omitempty"`
	AttachmentIds   []string               `protobuf:"bytes,4,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	RequestedAt     string                 `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveDeliveryRequest) Reset() {
	*x = SaveDeliveryRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDeliveryRequest) ProtoMessage() {}

func (x *SaveDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDeliveryRequest.ProtoReflect.Descriptor instead.
func (*SaveDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{23}
}

func (x *SaveDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SaveDeliveryRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *SaveDeliveryRequest) GetDeliveryMessage() string {
	if x != nil {
		return x.DeliveryMessage
	}
	return ""
}

func (x *SaveDeliveryRequest) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *SaveDeliveryRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type SaveDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDeliveryResponse) Reset() {
	*x = SaveDeliveryResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDeliveryResponse) ProtoMessage() {}

func (x *SaveDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDeliveryResponse.ProtoReflect.Descriptor instead.
func (*SaveDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{24}
}

func (x *SaveDeliveryResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkReleasePendingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentReleaseId string                 `protobuf:"bytes,2,opt,name=payment_release_id,json=paymentReleaseId,proto3" json:"payment_release_id,omitempty"`
	RequestedAt      string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarkReleasePendingRequest) Reset() {
	*x = MarkReleasePendingRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReleasePendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReleasePendingRequest) ProtoMessage() {}

func (x *MarkReleasePendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReleasePendingRequest.ProtoReflect.Descriptor instead.
func (*MarkReleasePendingRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{25}
}

func (x *MarkReleasePendingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkReleasePendingRequest) GetPaymentReleaseId() string {
	if x != nil {
		return x.PaymentReleaseId
	}
	return ""
}

func (x *MarkReleasePendingRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkReleasePendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReleasePendingResponse) Reset() {
	*x = MarkReleasePendingResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReleasePendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReleasePendingResponse) ProtoMessage() {}

func (x *MarkReleasePendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReleasePendingResponse.ProtoReflect.Descriptor instead.
func (*MarkReleasePendingResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{26}
}

func (x *MarkReleasePendingResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type RequestRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRevisionRequest) Reset() {
	*x = RequestRevisionRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRevisionRequest) ProtoMessage() {}

func (x *RequestRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRevisionRequest.ProtoReflect.Descriptor instead.
func (*RequestRevisionRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{27}
}

func (x *RequestRevisionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRevisionRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *RequestRevisionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestRevisionRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type RequestRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRevisionResponse) Reset() {
	*x = RequestRevisionResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRevisionResponse) ProtoMessage() {}

func (x *RequestRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRevisionResponse.ProtoReflect.Descriptor instead.
func (*RequestRevisionResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{28}
}

func (x *RequestRevisionResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type OpenDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDisputeRequest) Reset() {
	*x = OpenDisputeRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDisputeRequest) ProtoMessage() {}

func (x *OpenDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDisputeRequest.ProtoReflect.Descriptor instead.
func (*OpenDisputeRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{29}
}

func (x *OpenDisputeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenDisputeRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *OpenDisputeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OpenDisputeRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type OpenDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDisputeResponse) Reset() {
	*x = OpenDisputeResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDisputeResponse) ProtoMessage() {}

func (x *OpenDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDisputeResponse.ProtoReflect.Descriptor instead.
func (*OpenDisputeResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{30}
}

func (x *OpenDisputeResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkOrderCompletedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentReleaseId string                 `protobuf:"bytes,2,opt,name=payment_release_id,json=paymentReleaseId,proto3" json:"payment_release_id,omitempty"`
	RequestedAt      string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarkOrderCompletedRequest) Reset() {
	*x = MarkOrderCompletedRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderCompletedRequest) ProtoMessage() {}

func (x *MarkOrderCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkOrderCompletedRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{31}
}

func (x *MarkOrderCompletedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkOrderCompletedRequest) GetPaymentReleaseId() string {
	if x != nil {
		return x.PaymentReleaseId
	}
	return ""
}

func (x *MarkOrderCompletedRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkOrderCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderCompletedResponse) Reset() {
	*x = MarkOrderCompletedResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderCompletedResponse) ProtoMessage() {}

func (x *MarkOrderCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkOrderCompletedResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{32}
}

func (x *MarkOrderCompletedResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkReleaseFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReleaseFailedRequest) Reset() {
	*x = MarkReleaseFailedRequest{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReleaseFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReleaseFailedRequest) ProtoMessage() {}

func (x *MarkReleaseFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReleaseFailedRequest.ProtoReflect.Descriptor instead.
func (*MarkReleaseFailedRequest) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{33}
}

func (x *MarkReleaseFailedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkReleaseFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MarkReleaseFailedRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type MarkReleaseFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderSnapshot         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReleaseFailedResponse) Reset() {
	*x = MarkReleaseFailedResponse{}
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReleaseFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReleaseFailedResponse) ProtoMessage() {}

func (x *MarkReleaseFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderwrite_v1_orderwrite_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReleaseFailedResponse.ProtoReflect.Descriptor instead.
func (*MarkReleaseFailedResponse) Descriptor() ([]byte, []int) {
	return file_orderwrite_v1_orderwrite_proto_rawDescGZIP(), []int{34}
}

func (x *MarkReleaseFailedResponse) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orderwrite_v1_orderwrite_proto protoreflect.FileDescriptor

const file_orderwrite_v1_orderwrite_proto_rawDesc = "" +
	"\n" +
	"\x1eorderwrite/v1/orderwrite.proto\x12\rorderwrite.v1\"\x93\b\n" +
	"\rOrderSnapshot\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\asaga_id\x18\x02 \x01(\tR\x06sagaId\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x04 \x01(\tR\fsellerUserId\x12\x15\n" +
	"\x06gig_id\x18\x05 \x01(\tR\x05gigId\x12,\n" +
	"\x12gig_title_snapshot\x18\x06 \x01(\tR\x10gigTitleSnapshot\x12\x1d\n" +
	"\n" +
	"package_id\x18\a \x01(\tR\tpackageId\x124\n" +
	"\x16package_title_snapshot\x18\b \x01(\tR\x14packageTitleSnapshot\x12@\n" +
	"\x1cpackage_description_snapshot\x18\t \x01(\tR\x1apackageDescriptionSnapshot\x122\n" +
	"\x15price_amount_snapshot\x18\n" +
	" \x01(\x03R\x13priceAmountSnapshot\x126\n" +
	"\x17price_currency_snapshot\x18\v \x01(\tR\x15priceCurrencySnapshot\x124\n" +
	"\x16delivery_days_snapshot\x18\f \x01(\x05R\x14deliveryDaysSnapshot\x126\n" +
	"\x17revision_count_snapshot\x18\r \x01(\x05R\x15revisionCountSnapshot\x122\n" +
	"\x15buyer_initial_message\x18\x0e \x01(\tR\x13buyerInitialMessage\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12*\n" +
	"\x11payment_intent_id\x18\x10 \x01(\tR\x0fpaymentIntentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tfunded_at\x18\x13 \x01(\tR\bfundedAt\x12!\n" +
	"\fdelivered_at\x18\x14 \x01(\tR\vdeliveredAt\x12!\n" +
	"\fcompleted_at\x18\x15 \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vdisputed_at\x18\x16 \x01(\tR\n" +
	"disputedAt\x12.\n" +
	"\x13revision_count_used\x18\x17 \x01(\x05R\x11revisionCountUsed\x126\n" +
	"\x17buyer_response_deadline\x18\x18 \x01(\tR\x15buyerResponseDeadline\x12,\n" +
	"\x12payment_release_id\x18\x19 \x01(\tR\x10paymentReleaseId\"A\n" +
	"\x13OrderQuestionOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xd9\x01\n" +
	"\x15OrderQuestionSnapshot\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12<\n" +
	"\aoptions\x18\x05 \x03(\v2\".orderwrite.v1.OrderQuestionOptionR\aoptions\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"D\n" +
	"\vOrderAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc5\x01\n" +
	"\x12AttachmentSnapshot\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xdd\x05\n" +
	"\x17CreateDraftOrderRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x04 \x01(\tR\fsellerUserId\x12\x15\n" +
	"\x06gig_id\x18\x05 \x01(\tR\x05gigId\x12,\n" +
	"\x12gig_title_snapshot\x18\x06 \x01(\tR\x10gigTitleSnapshot\x12\x1d\n" +
	"\n" +
	"package_id\x18\a \x01(\tR\tpackageId\x124\n" +
	"\x16package_title_snapshot\x18\b \x01(\tR\x14packageTitleSnapshot\x12@\n" +
	"\x1cpackage_description_snapshot\x18\t \x01(\tR\x1apackageDescriptionSnapshot\x122\n" +
	"\x15price_amount_snapshot\x18\n" +
	" \x01(\x03R\x13priceAmountSnapshot\x126\n" +
	"\x17price_currency_snapshot\x18\v \x01(\tR\x15priceCurrencySnapshot\x124\n" +
	"\x16delivery_days_snapshot\x18\f \x01(\x05R\x14deliveryDaysSnapshot\x126\n" +
	"\x17revision_count_snapshot\x18\r \x01(\x05R\x15revisionCountSnapshot\x12B\n" +
	"\tquestions\x18\x0e \x03(\v2$.orderwrite.v1.OrderQuestionSnapshotR\tquestions\x12'\n" +
	"\x0fidempotency_key\x18\x0f \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\frequested_at\x18\x10 \x01(\tR\vrequestedAt\"\x92\x01\n" +
	"\x18CreateDraftOrderResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\x12B\n" +
	"\tquestions\x18\x02 \x03(\v2$.orderwrite.v1.OrderQuestionSnapshotR\tquestions\"\xb7\x01\n" +
	"\x1dSaveRequirementAnswersRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x124\n" +
	"\aanswers\x18\x03 \x03(\v2\x1a.orderwrite.v1.OrderAnswerR\aanswers\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"T\n" +
	"\x1eSaveRequirementAnswersResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x9c\x01\n" +
	"\x1eSaveBuyerInitialMessageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"U\n" +
	"\x1fSaveBuyerInitialMessageResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x95\x02\n" +
	"\x18AttachFileToOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12#\n" +
	"\rattachment_id\x18\x03 \x01(\tR\fattachmentId\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12!\n" +
	"\frequested_at\x18\b \x01(\tR\vrequestedAt\"\x92\x01\n" +
	"\x19AttachFileToOrderResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\x12A\n" +
	"\n" +
	"attachment\x18\x02 \x01(\v2!.orderwrite.v1.AttachmentSnapshotR\n" +
	"attachment\"_\n" +
	"\x1eGetOrderPaymentSnapshotRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\"U\n" +
	"\x1fGetOrderPaymentSnapshotResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x9b\x01\n" +
	"\x19MarkPaymentPendingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\x03 \x01(\tR\vcheckoutUrl\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"P\n" +
	"\x1aMarkPaymentPendingResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"u\n" +
	"\x16MarkOrderFundedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"M\n" +
	"\x17MarkOrderFundedResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x8f\x01\n" +
	"\x18MarkPaymentFailedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"O\n" +
	"\x19MarkPaymentFailedResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"=\n" +
	" GetOrderLifecycleSnapshotRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"W\n" +
	"!GetOrderLifecycleSnapshotResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\xcb\x01\n" +
	"\x13SaveDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12$\n" +
	"\x0eseller_user_id\x18\x02 \x01(\tR\fsellerUserId\x12)\n" +
	"\x10delivery_message\x18\x03 \x01(\tR\x0fdeliveryMessage\x12%\n" +
	"\x0eattachment_ids\x18\x04 \x03(\tR\rattachmentIds\x12!\n" +
	"\frequested_at\x18\x05 \x01(\tR\vrequestedAt\"J\n" +
	"\x14SaveDeliveryResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x87\x01\n" +
	"\x19MarkReleasePendingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x12payment_release_id\x18\x02 \x01(\tR\x10paymentReleaseId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"P\n" +
	"\x1aMarkReleasePendingResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x92\x01\n" +
	"\x16RequestRevisionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"M\n" +
	"\x17RequestRevisionResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x8e\x01\n" +
	"\x12OpenDisputeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"I\n" +
	"\x13OpenDisputeResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"\x87\x01\n" +
	"\x19MarkOrderCompletedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x12payment_release_id\x18\x02 \x01(\tR\x10paymentReleaseId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"P\n" +
	"\x1aMarkOrderCompletedResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order\"p\n" +
	"\x18MarkReleaseFailedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"O\n" +
	"\x19MarkReleaseFailedResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orderwrite.v1.OrderSnapshotR\x05order2\xcf\f\n" +
	"\x11OrderWriteService\x12c\n" +
	"\x10CreateDraftOrder\x12&.orderwrite.v1.CreateDraftOrderRequest\x1a'.orderwrite.v1.CreateDraftOrderResponse\x12u\n" +
	"\x16SaveRequirementAnswers\x12,.orderwrite.v1.SaveRequirementAnswersRequest\x1a-.orderwrite.v1.SaveRequirementAnswersResponse\x12x\n" +
	"\x17SaveBuyerInitialMessage\x12-.orderwrite.v1.SaveBuyerInitialMessageRequest\x1a..orderwrite.v1.SaveBuyerInitialMessageResponse\x12f\n" +
	"\x11AttachFileToOrder\x12'.orderwrite.v1.AttachFileToOrderRequest\x1a(.orderwrite.v1.AttachFileToOrderResponse\x12x\n" +
	"\x17GetOrderPaymentSnapshot\x12-.orderwrite.v1.GetOrderPaymentSnapshotRequest\x1a..orderwrite.v1.GetOrderPaymentSnapshotResponse\x12i\n" +
	"\x12MarkPaymentPending\x12(.orderwrite.v1.MarkPaymentPendingRequest\x1a).orderwrite.v1.MarkPaymentPendingResponse\x12`\n" +
	"\x0fMarkOrderFunded\x12%.orderwrite.v1.MarkOrderFundedRequest\x1a&.orderwrite.v1.MarkOrderFundedResponse\x12f\n" +
	"\x11MarkPaymentFailed\x12'.orderwrite.v1.MarkPaymentFailedRequest\x1a(.orderwrite.v1.MarkPaymentFailedResponse\x12~\n" +
	"\x19GetOrderLifecycleSnapshot\x12/.orderwrite.v1.GetOrderLifecycleSnapshotRequest\x1a0.orderwrite.v1.GetOrderLifecycleSnapshotResponse\x12W\n" +
	"\fSaveDelivery\x12\".orderwrite.v1.SaveDeliveryRequest\x1a#.orderwrite.v1.SaveDeliveryResponse\x12i\n" +
	"\x12MarkReleasePending\x12(.orderwrite.v1.MarkReleasePendingRequest\x1a).orderwrite.v1.MarkReleasePendingResponse\x12`\n" +
	"\x0fRequestRevision\x12%.orderwrite.v1.RequestRevisionRequest\x1a&.orderwrite.v1.RequestRevisionResponse\x12T\n" +
	"\vOpenDispute\x12!.orderwrite.v1.OpenDisputeRequest\x1a\".orderwrite.v1.OpenDisputeResponse\x12i\n" +
	"\x12MarkOrderCompleted\x12(.orderwrite.v1.MarkOrderCompletedRequest\x1a).orderwrite.v1.MarkOrderCompletedResponse\x12f\n" +
	"\x11MarkReleaseFailed\x12'.orderwrite.v1.MarkReleaseFailedRequest\x1a(.orderwrite.v1.MarkReleaseFailedResponseBJZHgithub.com/ofm-microservices/ofm-common/proto/orderwrite/v1;orderwritev1b\x06proto3"

var (
	file_orderwrite_v1_orderwrite_proto_rawDescOnce sync.Once
	file_orderwrite_v1_orderwrite_proto_rawDescData []byte
)

func file_orderwrite_v1_orderwrite_proto_rawDescGZIP() []byte {
	file_orderwrite_v1_orderwrite_proto_rawDescOnce.Do(func() {
		file_orderwrite_v1_orderwrite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderwrite_v1_orderwrite_proto_rawDesc), len(file_orderwrite_v1_orderwrite_proto_rawDesc)))
	})
	return file_orderwrite_v1_orderwrite_proto_rawDescData
}

var file_orderwrite_v1_orderwrite_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_orderwrite_v1_orderwrite_proto_goTypes = []any{
	(*OrderSnapshot)(nil),                     // 0: orderwrite.v1.OrderSnapshot
	(*OrderQuestionOption)(nil),               // 1: orderwrite.v1.OrderQuestionOption
	(*OrderQuestionSnapshot)(nil),             // 2: orderwrite.v1.OrderQuestionSnapshot
	(*OrderAnswer)(nil),                       // 3: orderwrite.v1.OrderAnswer
	(*AttachmentSnapshot)(nil),                // 4: orderwrite.v1.AttachmentSnapshot
	(*CreateDraftOrderRequest)(nil),           // 5: orderwrite.v1.CreateDraftOrderRequest
	(*CreateDraftOrderResponse)(nil),          // 6: orderwrite.v1.CreateDraftOrderResponse
	(*SaveRequirementAnswersRequest)(nil),     // 7: orderwrite.v1.SaveRequirementAnswersRequest
	(*SaveRequirementAnswersResponse)(nil),    // 8: orderwrite.v1.SaveRequirementAnswersResponse
	(*SaveBuyerInitialMessageRequest)(nil),    // 9: orderwrite.v1.SaveBuyerInitialMessageRequest
	(*SaveBuyerInitialMessageResponse)(nil),   // 10: orderwrite.v1.SaveBuyerInitialMessageResponse
	(*AttachFileToOrderRequest)(nil),          // 11: orderwrite.v1.AttachFileToOrderRequest
	(*AttachFileToOrderResponse)(nil),         // 12: orderwrite.v1.AttachFileToOrderResponse
	(*GetOrderPaymentSnapshotRequest)(nil),    // 13: orderwrite.v1.GetOrderPaymentSnapshotRequest
	(*GetOrderPaymentSnapshotResponse)(nil),   // 14: orderwrite.v1.GetOrderPaymentSnapshotResponse
	(*MarkPaymentPendingRequest)(nil),         // 15: orderwrite.v1.MarkPaymentPendingRequest
	(*MarkPaymentPendingResponse)(nil),        // 16: orderwrite.v1.MarkPaymentPendingResponse
	(*MarkOrderFundedRequest)(nil),            // 17: orderwrite.v1.MarkOrderFundedRequest
	(*MarkOrderFundedResponse)(nil),           // 18: orderwrite.v1.MarkOrderFundedResponse
	(*MarkPaymentFailedRequest)(nil),          // 19: orderwrite.v1.MarkPaymentFailedRequest
	(*MarkPaymentFailedResponse)(nil),         // 20: orderwrite.v1.MarkPaymentFailedResponse
	(*GetOrderLifecycleSnapshotRequest)(nil),  // 21: orderwrite.v1.GetOrderLifecycleSnapshotRequest
	(*GetOrderLifecycleSnapshotResponse)(nil), // 22: orderwrite.v1.GetOrderLifecycleSnapshotResponse
	(*SaveDeliveryRequest)(nil),               // 23: orderwrite.v1.SaveDeliveryRequest
	(*SaveDeliveryResponse)(nil),              // 24: orderwrite.v1.SaveDeliveryResponse
	(*MarkReleasePendingRequest)(nil),         // 25: orderwrite.v1.MarkReleasePendingRequest
	(*MarkReleasePendingResponse)(nil),        // 26: orderwrite.v1.MarkReleasePendingResponse
	(*RequestRevisionRequest)(nil),            // 27: orderwrite.v1.RequestRevisionRequest
	(*RequestRevisionResponse)(nil),           // 28: orderwrite.v1.RequestRevisionResponse
	(*OpenDisputeRequest)(nil),                // 29: orderwrite.v1.OpenDisputeRequest
	(*OpenDisputeResponse)(nil),               // 30: orderwrite.v1.OpenDisputeResponse
	(*MarkOrderCompletedRequest)(nil),         // 31: orderwrite.v1.MarkOrderCompletedRequest
	(*MarkOrderCompletedResponse)(nil),        // 32: orderwrite.v1.MarkOrderCompletedResponse
	(*MarkReleaseFailedRequest)(nil),          // 33: orderwrite.v1.MarkReleaseFailedRequest
	(*MarkReleaseFailedResponse)(nil),         // 34: orderwrite.v1.MarkReleaseFailedResponse
}
var file_orderwrite_v1_orderwrite_proto_depIdxs = []int32{
	1,  // 0: orderwrite.v1.OrderQuestionSnapshot.options:type_name -> orderwrite.v1.OrderQuestionOption
	2,  // 1: orderwrite.v1.CreateDraftOrderRequest.questions:type_name -> orderwrite.v1.OrderQuestionSnapshot
	0,  // 2: orderwrite.v1.CreateDraftOrderResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	2,  // 3: orderwrite.v1.CreateDraftOrderResponse.questions:type_name -> orderwrite.v1.OrderQuestionSnapshot
	3,  // 4: orderwrite.v1.SaveRequirementAnswersRequest.answers:type_name -> orderwrite.v1.OrderAnswer
	0,  // 5: orderwrite.v1.SaveRequirementAnswersResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 6: orderwrite.v1.SaveBuyerInitialMessageResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 7: orderwrite.v1.AttachFileToOrderResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	4,  // 8: orderwrite.v1.AttachFileToOrderResponse.attachment:type_name -> orderwrite.v1.AttachmentSnapshot
	0,  // 9: orderwrite.v1.GetOrderPaymentSnapshotResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 10: orderwrite.v1.MarkPaymentPendingResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 11: orderwrite.v1.MarkOrderFundedResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 12: orderwrite.v1.MarkPaymentFailedResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 13: orderwrite.v1.GetOrderLifecycleSnapshotResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 14: orderwrite.v1.SaveDeliveryResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 15: orderwrite.v1.MarkReleasePendingResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 16: orderwrite.v1.RequestRevisionResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 17: orderwrite.v1.OpenDisputeResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 18: orderwrite.v1.MarkOrderCompletedResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	0,  // 19: orderwrite.v1.MarkReleaseFailedResponse.order:type_name -> orderwrite.v1.OrderSnapshot
	5,  // 20: orderwrite.v1.OrderWriteService.CreateDraftOrder:input_type -> orderwrite.v1.CreateDraftOrderRequest
	7,  // 21: orderwrite.v1.OrderWriteService.SaveRequirementAnswers:input_type -> orderwrite.v1.SaveRequirementAnswersRequest
	9,  // 22: orderwrite.v1.OrderWriteService.SaveBuyerInitialMessage:input_type -> orderwrite.v1.SaveBuyerInitialMessageRequest
	11, // 23: orderwrite.v1.OrderWriteService.AttachFileToOrder:input_type -> orderwrite.v1.AttachFileToOrderRequest
	13, // 24: orderwrite.v1.OrderWriteService.GetOrderPaymentSnapshot:input_type -> orderwrite.v1.GetOrderPaymentSnapshotRequest
	15, // 25: orderwrite.v1.OrderWriteService.MarkPaymentPending:input_type -> orderwrite.v1.MarkPaymentPendingRequest
	17, // 26: orderwrite.v1.OrderWriteService.MarkOrderFunded:input_type -> orderwrite.v1.MarkOrderFundedRequest
	19, // 27: orderwrite.v1.OrderWriteService.MarkPaymentFailed:input_type -> orderwrite.v1.MarkPaymentFailedRequest
	21, // 28: orderwrite.v1.OrderWriteService.GetOrderLifecycleSnapshot:input_type -> orderwrite.v1.GetOrderLifecycleSnapshotRequest
	23, // 29: orderwrite.v1.OrderWriteService.SaveDelivery:input_type -> orderwrite.v1.SaveDeliveryRequest
	25, // 30: orderwrite.v1.OrderWriteService.MarkReleasePending:input_type -> orderwrite.v1.MarkReleasePendingRequest
	27, // 31: orderwrite.v1.OrderWriteService.RequestRevision:input_type -> orderwrite.v1.RequestRevisionRequest
	29, // 32: orderwrite.v1.OrderWriteService.OpenDispute:input_type -> orderwrite.v1.OpenDisputeRequest
	31, // 33: orderwrite.v1.OrderWriteService.MarkOrderCompleted:input_type -> orderwrite.v1.MarkOrderCompletedRequest
	33, // 34: orderwrite.v1.OrderWriteService.MarkReleaseFailed:input_type -> orderwrite.v1.MarkReleaseFailedRequest
	6,  // 35: orderwrite.v1.OrderWriteService.CreateDraftOrder:output_type -> orderwrite.v1.CreateDraftOrderResponse
	8,  // 36: orderwrite.v1.OrderWriteService.SaveRequirementAnswers:output_type -> orderwrite.v1.SaveRequirementAnswersResponse
	10, // 37: orderwrite.v1.OrderWriteService.SaveBuyerInitialMessage:output_type -> orderwrite.v1.SaveBuyerInitialMessageResponse
	12, // 38: orderwrite.v1.OrderWriteService.AttachFileToOrder:output_type -> orderwrite.v1.AttachFileToOrderResponse
	14, // 39: orderwrite.v1.OrderWriteService.GetOrderPaymentSnapshot:output_type -> orderwrite.v1.GetOrderPaymentSnapshotResponse
	16, // 40: orderwrite.v1.OrderWriteService.MarkPaymentPending:output_type -> orderwrite.v1.MarkPaymentPendingResponse
	18, // 41: orderwrite.v1.OrderWriteService.MarkOrderFunded:output_type -> orderwrite.v1.MarkOrderFundedResponse
	20, // 42: orderwrite.v1.OrderWriteService.MarkPaymentFailed:output_type -> orderwrite.v1.MarkPaymentFailedResponse
	22, // 43: orderwrite.v1.OrderWriteService.GetOrderLifecycleSnapshot:output_type -> orderwrite.v1.GetOrderLifecycleSnapshotResponse
	24, // 44: orderwrite.v1.OrderWriteService.SaveDelivery:output_type -> orderwrite.v1.SaveDeliveryResponse
	26, // 45: orderwrite.v1.OrderWriteService.MarkReleasePending:output_type -> orderwrite.v1.MarkReleasePendingResponse
	28, // 46: orderwrite.v1.OrderWriteService.RequestRevision:output_type -> orderwrite.v1.RequestRevisionResponse
	30, // 47: orderwrite.v1.OrderWriteService.OpenDispute:output_type -> orderwrite.v1.OpenDisputeResponse
	32, // 48: orderwrite.v1.OrderWriteService.MarkOrderCompleted:output_type -> orderwrite.v1.MarkOrderCompletedResponse
	34, // 49: orderwrite.v1.OrderWriteService.MarkReleaseFailed:output_type -> orderwrite.v1.MarkReleaseFailedResponse
	35, // [35:50] is the sub-list for method output_type
	20, // [20:35] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_orderwrite_v1_orderwrite_proto_init() }
func file_orderwrite_v1_orderwrite_proto_init() {
	if File_orderwrite_v1_orderwrite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderwrite_v1_orderwrite_proto_rawDesc), len(file_orderwrite_v1_orderwrite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderwrite_v1_orderwrite_proto_goTypes,
		DependencyIndexes: file_orderwrite_v1_orderwrite_proto_depIdxs,
		MessageInfos:      file_orderwrite_v1_orderwrite_proto_msgTypes,
	}.Build()
	File_orderwrite_v1_orderwrite_proto = out.File
	file_orderwrite_v1_orderwrite_proto_goTypes = nil
	file_orderwrite_v1_orderwrite_proto_depIdxs = nil
}
