// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: search/v1/search.proto

// Package search.v1 defines the public gig search contract shared between
// api-gateway and search-service.

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchResult describes one searchable gig card.
type SearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture        string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	ReviewsCount   int64                  `protobuf:"varint,5,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	Rating         float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	MinPrice       int64                  `protobuf:"varint,7,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	Slug           string                 `protobuf:"bytes,8,opt,name=slug,proto3" json:"slug,omitempty"`
	FreelancerId   string                 `protobuf:"bytes,9,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	PublishedAt    string                 `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	SellerUsername string                 `protobuf:"bytes,11,opt,name=seller_username,json=sellerUsername,proto3" json:"seller_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchResult) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *SearchResult) GetReviewsCount() int64 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

func (x *SearchResult) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SearchResult) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchResult) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchResult) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *SearchResult) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *SearchResult) GetSellerUsername() string {
	if x != nil {
		return x.SellerUsername
	}
	return ""
}

// SearchRequest carries the public search query and paging controls.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Sort          int32                  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SearchRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *SearchRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// SearchResponse returns a single page of gig search results.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*SearchResult        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetServices() []*SearchResult {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *SearchResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\"\xcf\x02\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12#\n" +
	"\rreviews_count\x18\x05 \x01(\x03R\freviewsCount\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12\x1b\n" +
	"\tmin_price\x18\a \x01(\x03R\bminPrice\x12\x12\n" +
	"\x04slug\x18\b \x01(\tR\x04slug\x12#\n" +
	"\rfreelancer_id\x18\t \x01(\tR\ffreelancerId\x12!\n" +
	"\fpublished_at\x18\n" +
	" \x01(\tR\vpublishedAt\x12'\n" +
	"\x0fseller_username\x18\v \x01(\tR\x0esellerUsername\"g\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\x05R\x04sort\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"x\n" +
	"\x0eSearchResponse\x123\n" +
	"\bservices\x18\x01 \x03(\v2\x17.search.v1.SearchResultR\bservices\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2N\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponseBBZ@github.com/ofm-microservices/ofm-common/proto/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchResult)(nil),   // 0: search.v1.SearchResult
	(*SearchRequest)(nil),  // 1: search.v1.SearchRequest
	(*SearchResponse)(nil), // 2: search.v1.SearchResponse
}
var file_search_v1_search_proto_depIdxs = []int32{
	0, // 0: search.v1.SearchResponse.services:type_name -> search.v1.SearchResult
	1, // 1: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	2, // 2: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
