// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: common/v1/common.proto

// Package common.v1 defines reusable cross-service proto types.

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParticipantRole is a shared view-role enum reused by user-scoped resources.
type ParticipantRole int32

const (
	ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED ParticipantRole = 0
	ParticipantRole_PARTICIPANT_ROLE_BUYER       ParticipantRole = 1
	ParticipantRole_PARTICIPANT_ROLE_SELLER      ParticipantRole = 2
)

// Enum value maps for ParticipantRole.
var (
	ParticipantRole_name = map[int32]string{
		0: "PARTICIPANT_ROLE_UNSPECIFIED",
		1: "PARTICIPANT_ROLE_BUYER",
		2: "PARTICIPANT_ROLE_SELLER",
	}
	ParticipantRole_value = map[string]int32{
		"PARTICIPANT_ROLE_UNSPECIFIED": 0,
		"PARTICIPANT_ROLE_BUYER":       1,
		"PARTICIPANT_ROLE_SELLER":      2,
	}
)

func (x ParticipantRole) Enum() *ParticipantRole {
	p := new(ParticipantRole)
	*p = x
	return p
}

func (x ParticipantRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantRole) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (ParticipantRole) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x ParticipantRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantRole.Descriptor instead.
func (ParticipantRole) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\tcommon.v1*l\n" +
	"\x0fParticipantRole\x12 \n" +
	"\x1cPARTICIPANT_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PARTICIPANT_ROLE_BUYER\x10\x01\x12\x1b\n" +
	"\x17PARTICIPANT_ROLE_SELLER\x10\x02BBZ@github.com/ofm-microservices/ofm-common/proto/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_common_proto_goTypes = []any{
	(ParticipantRole)(0), // 0: common.v1.ParticipantRole
}
var file_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
