// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentcheckout/v1/paymentcheckout.proto

// Package paymentcheckout.v1 defines the synchronous checkout-session contract
// used by order-saga-service and payment-service.

package paymentcheckoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCheckoutSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SagaId         string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId    string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUserId   string                 `protobuf:"bytes,4,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Title          string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestedAt    string                 `protobuf:"bytes,9,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_paymentcheckout_v1_paymentcheckout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentcheckout_v1_paymentcheckout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_paymentcheckout_v1_paymentcheckout_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCheckoutSessionRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CreateCheckoutSessionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type CreateCheckoutSessionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrderId               string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId             string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl           string                 `protobuf:"bytes,3,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	StripePaymentIntentId string                 `protobuf:"bytes,4,opt,name=stripe_payment_intent_id,json=stripePaymentIntentId,proto3" json:"stripe_payment_intent_id,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OccurredAt            string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_paymentcheckout_v1_paymentcheckout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentcheckout_v1_paymentcheckout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_paymentcheckout_v1_paymentcheckout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCheckoutSessionResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetStripePaymentIntentId() string {
	if x != nil {
		return x.StripePaymentIntentId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

var File_paymentcheckout_v1_paymentcheckout_proto protoreflect.FileDescriptor

const file_paymentcheckout_v1_paymentcheckout_proto_rawDesc = "" +
	"\n" +
	"(paymentcheckout/v1/paymentcheckout.proto\x12\x12paymentcheckout.v1\"\xbd\x02\n" +
	"\x1cCreateCheckoutSessionRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x0eseller_user_id\x18\x04 \x01(\tR\fsellerUserId\x12!\n" +
	"\famount_cents\x18\x05 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\frequested_at\x18\t \x01(\tR\vrequestedAt\"\xee\x01\n" +
	"\x1dCreateCheckoutSessionResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\x03 \x01(\tR\vcheckoutUrl\x127\n" +
	"\x18stripe_payment_intent_id\x18\x04 \x01(\tR\x15stripePaymentIntentId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt2\x96\x01\n" +
	"\x16PaymentCheckoutService\x12|\n" +
	"\x15CreateCheckoutSession\x120.paymentcheckout.v1.CreateCheckoutSessionRequest\x1a1.paymentcheckout.v1.CreateCheckoutSessionResponseBTZRgithub.com/ofm-microservices/ofm-common/proto/paymentcheckout/v1;paymentcheckoutv1b\x06proto3"

var (
	file_paymentcheckout_v1_paymentcheckout_proto_rawDescOnce sync.Once
	file_paymentcheckout_v1_paymentcheckout_proto_rawDescData []byte
)

func file_paymentcheckout_v1_paymentcheckout_proto_rawDescGZIP() []byte {
	file_paymentcheckout_v1_paymentcheckout_proto_rawDescOnce.Do(func() {
		file_paymentcheckout_v1_paymentcheckout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentcheckout_v1_paymentcheckout_proto_rawDesc), len(file_paymentcheckout_v1_paymentcheckout_proto_rawDesc)))
	})
	return file_paymentcheckout_v1_paymentcheckout_proto_rawDescData
}

var file_paymentcheckout_v1_paymentcheckout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paymentcheckout_v1_paymentcheckout_proto_goTypes = []any{
	(*CreateCheckoutSessionRequest)(nil),  // 0: paymentcheckout.v1.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil), // 1: paymentcheckout.v1.CreateCheckoutSessionResponse
}
var file_paymentcheckout_v1_paymentcheckout_proto_depIdxs = []int32{
	0, // 0: paymentcheckout.v1.PaymentCheckoutService.CreateCheckoutSession:input_type -> paymentcheckout.v1.CreateCheckoutSessionRequest
	1, // 1: paymentcheckout.v1.PaymentCheckoutService.CreateCheckoutSession:output_type -> paymentcheckout.v1.CreateCheckoutSessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentcheckout_v1_paymentcheckout_proto_init() }
func file_paymentcheckout_v1_paymentcheckout_proto_init() {
	if File_paymentcheckout_v1_paymentcheckout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentcheckout_v1_paymentcheckout_proto_rawDesc), len(file_paymentcheckout_v1_paymentcheckout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentcheckout_v1_paymentcheckout_proto_goTypes,
		DependencyIndexes: file_paymentcheckout_v1_paymentcheckout_proto_depIdxs,
		MessageInfos:      file_paymentcheckout_v1_paymentcheckout_proto_msgTypes,
	}.Build()
	File_paymentcheckout_v1_paymentcheckout_proto = out.File
	file_paymentcheckout_v1_paymentcheckout_proto_goTypes = nil
	file_paymentcheckout_v1_paymentcheckout_proto_depIdxs = nil
}
