// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: paymentcheckout/v1/paymentcheckout.proto

// Package paymentcheckout.v1 defines the synchronous checkout-session contract
// used by order-saga-service and payment-service.

package paymentcheckoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentCheckoutService_CreateCheckoutSession_FullMethodName = "/paymentcheckout.v1.PaymentCheckoutService/CreateCheckoutSession"
	PaymentCheckoutService_ReleaseFunds_FullMethodName          = "/paymentcheckout.v1.PaymentCheckoutService/ReleaseFunds"
	PaymentCheckoutService_GetReleaseByOrderId_FullMethodName   = "/paymentcheckout.v1.PaymentCheckoutService/GetReleaseByOrderId"
)

// PaymentCheckoutServiceClient is the client API for PaymentCheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentCheckoutService owns checkout-session creation.
type PaymentCheckoutServiceClient interface {
	CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error)
	ReleaseFunds(ctx context.Context, in *ReleaseFundsRequest, opts ...grpc.CallOption) (*ReleaseFundsResponse, error)
	GetReleaseByOrderId(ctx context.Context, in *GetReleaseByOrderIdRequest, opts ...grpc.CallOption) (*GetReleaseByOrderIdResponse, error)
}

type paymentCheckoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentCheckoutServiceClient(cc grpc.ClientConnInterface) PaymentCheckoutServiceClient {
	return &paymentCheckoutServiceClient{cc}
}

func (c *paymentCheckoutServiceClient) CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, PaymentCheckoutService_CreateCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentCheckoutServiceClient) ReleaseFunds(ctx context.Context, in *ReleaseFundsRequest, opts ...grpc.CallOption) (*ReleaseFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseFundsResponse)
	err := c.cc.Invoke(ctx, PaymentCheckoutService_ReleaseFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentCheckoutServiceClient) GetReleaseByOrderId(ctx context.Context, in *GetReleaseByOrderIdRequest, opts ...grpc.CallOption) (*GetReleaseByOrderIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReleaseByOrderIdResponse)
	err := c.cc.Invoke(ctx, PaymentCheckoutService_GetReleaseByOrderId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentCheckoutServiceServer is the server API for PaymentCheckoutService service.
// All implementations should embed UnimplementedPaymentCheckoutServiceServer
// for forward compatibility.
//
// PaymentCheckoutService owns checkout-session creation.
type PaymentCheckoutServiceServer interface {
	CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error)
	ReleaseFunds(context.Context, *ReleaseFundsRequest) (*ReleaseFundsResponse, error)
	GetReleaseByOrderId(context.Context, *GetReleaseByOrderIdRequest) (*GetReleaseByOrderIdResponse, error)
}

// UnimplementedPaymentCheckoutServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentCheckoutServiceServer struct{}

func (UnimplementedPaymentCheckoutServiceServer) CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCheckoutSession not implemented")
}
func (UnimplementedPaymentCheckoutServiceServer) ReleaseFunds(context.Context, *ReleaseFundsRequest) (*ReleaseFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseFunds not implemented")
}
func (UnimplementedPaymentCheckoutServiceServer) GetReleaseByOrderId(context.Context, *GetReleaseByOrderIdRequest) (*GetReleaseByOrderIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReleaseByOrderId not implemented")
}
func (UnimplementedPaymentCheckoutServiceServer) testEmbeddedByValue() {}

// UnsafePaymentCheckoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentCheckoutServiceServer will
// result in compilation errors.
type UnsafePaymentCheckoutServiceServer interface {
	mustEmbedUnimplementedPaymentCheckoutServiceServer()
}

func RegisterPaymentCheckoutServiceServer(s grpc.ServiceRegistrar, srv PaymentCheckoutServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentCheckoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentCheckoutService_ServiceDesc, srv)
}

func _PaymentCheckoutService_CreateCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCheckoutServiceServer).CreateCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentCheckoutService_CreateCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCheckoutServiceServer).CreateCheckoutSession(ctx, req.(*CreateCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentCheckoutService_ReleaseFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCheckoutServiceServer).ReleaseFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentCheckoutService_ReleaseFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCheckoutServiceServer).ReleaseFunds(ctx, req.(*ReleaseFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentCheckoutService_GetReleaseByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCheckoutServiceServer).GetReleaseByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentCheckoutService_GetReleaseByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCheckoutServiceServer).GetReleaseByOrderId(ctx, req.(*GetReleaseByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentCheckoutService_ServiceDesc is the grpc.ServiceDesc for PaymentCheckoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentCheckoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentcheckout.v1.PaymentCheckoutService",
	HandlerType: (*PaymentCheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheckoutSession",
			Handler:    _PaymentCheckoutService_CreateCheckoutSession_Handler,
		},
		{
			MethodName: "ReleaseFunds",
			Handler:    _PaymentCheckoutService_ReleaseFunds_Handler,
		},
		{
			MethodName: "GetReleaseByOrderId",
			Handler:    _PaymentCheckoutService_GetReleaseByOrderId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentcheckout/v1/paymentcheckout.proto",
}
