// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: user/v1/query.proto

// Package user.v1 defines the user ownership queries shared with
// registration-saga-service.

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserQueryService_ExistsByUsername_FullMethodName          = "/user.v1.UserQueryService/ExistsByUsername"
	UserQueryService_ActivateUser_FullMethodName              = "/user.v1.UserQueryService/ActivateUser"
	UserQueryService_DeactivateUser_FullMethodName            = "/user.v1.UserQueryService/DeactivateUser"
	UserQueryService_GetUserPreviewByID_FullMethodName        = "/user.v1.UserQueryService/GetUserPreviewByID"
	UserQueryService_GetDetailedUserByUsername_FullMethodName = "/user.v1.UserQueryService/GetDetailedUserByUsername"
)

// UserQueryServiceClient is the client API for UserQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserQueryService exposes read-only user ownership checks over gRPC.
type UserQueryServiceClient interface {
	ExistsByUsername(ctx context.Context, in *ExistsByUsernameRequest, opts ...grpc.CallOption) (*ExistsByUsernameResponse, error)
	ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error)
	DeactivateUser(ctx context.Context, in *DeactivateUserRequest, opts ...grpc.CallOption) (*DeactivateUserResponse, error)
	GetUserPreviewByID(ctx context.Context, in *GetUserPreviewByIDRequest, opts ...grpc.CallOption) (*GetUserPreviewByIDResponse, error)
	GetDetailedUserByUsername(ctx context.Context, in *GetDetailedUserByUsernameRequest, opts ...grpc.CallOption) (*GetDetailedUserByUsernameResponse, error)
}

type userQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryServiceClient(cc grpc.ClientConnInterface) UserQueryServiceClient {
	return &userQueryServiceClient{cc}
}

func (c *userQueryServiceClient) ExistsByUsername(ctx context.Context, in *ExistsByUsernameRequest, opts ...grpc.CallOption) (*ExistsByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsByUsernameResponse)
	err := c.cc.Invoke(ctx, UserQueryService_ExistsByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryServiceClient) ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateUserResponse)
	err := c.cc.Invoke(ctx, UserQueryService_ActivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryServiceClient) DeactivateUser(ctx context.Context, in *DeactivateUserRequest, opts ...grpc.CallOption) (*DeactivateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateUserResponse)
	err := c.cc.Invoke(ctx, UserQueryService_DeactivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryServiceClient) GetUserPreviewByID(ctx context.Context, in *GetUserPreviewByIDRequest, opts ...grpc.CallOption) (*GetUserPreviewByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPreviewByIDResponse)
	err := c.cc.Invoke(ctx, UserQueryService_GetUserPreviewByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryServiceClient) GetDetailedUserByUsername(ctx context.Context, in *GetDetailedUserByUsernameRequest, opts ...grpc.CallOption) (*GetDetailedUserByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailedUserByUsernameResponse)
	err := c.cc.Invoke(ctx, UserQueryService_GetDetailedUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServiceServer is the server API for UserQueryService service.
// All implementations should embed UnimplementedUserQueryServiceServer
// for forward compatibility.
//
// UserQueryService exposes read-only user ownership checks over gRPC.
type UserQueryServiceServer interface {
	ExistsByUsername(context.Context, *ExistsByUsernameRequest) (*ExistsByUsernameResponse, error)
	ActivateUser(context.Context, *ActivateUserRequest) (*ActivateUserResponse, error)
	DeactivateUser(context.Context, *DeactivateUserRequest) (*DeactivateUserResponse, error)
	GetUserPreviewByID(context.Context, *GetUserPreviewByIDRequest) (*GetUserPreviewByIDResponse, error)
	GetDetailedUserByUsername(context.Context, *GetDetailedUserByUsernameRequest) (*GetDetailedUserByUsernameResponse, error)
}

// UnimplementedUserQueryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserQueryServiceServer struct{}

func (UnimplementedUserQueryServiceServer) ExistsByUsername(context.Context, *ExistsByUsernameRequest) (*ExistsByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsByUsername not implemented")
}
func (UnimplementedUserQueryServiceServer) ActivateUser(context.Context, *ActivateUserRequest) (*ActivateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateUser not implemented")
}
func (UnimplementedUserQueryServiceServer) DeactivateUser(context.Context, *DeactivateUserRequest) (*DeactivateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateUser not implemented")
}
func (UnimplementedUserQueryServiceServer) GetUserPreviewByID(context.Context, *GetUserPreviewByIDRequest) (*GetUserPreviewByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPreviewByID not implemented")
}
func (UnimplementedUserQueryServiceServer) GetDetailedUserByUsername(context.Context, *GetDetailedUserByUsernameRequest) (*GetDetailedUserByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailedUserByUsername not implemented")
}
func (UnimplementedUserQueryServiceServer) testEmbeddedByValue() {}

// UnsafeUserQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServiceServer will
// result in compilation errors.
type UnsafeUserQueryServiceServer interface {
	mustEmbedUnimplementedUserQueryServiceServer()
}

func RegisterUserQueryServiceServer(s grpc.ServiceRegistrar, srv UserQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedUserQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserQueryService_ServiceDesc, srv)
}

func _UserQueryService_ExistsByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).ExistsByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQueryService_ExistsByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).ExistsByUsername(ctx, req.(*ExistsByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQueryService_ActivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).ActivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQueryService_ActivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).ActivateUser(ctx, req.(*ActivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQueryService_DeactivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).DeactivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQueryService_DeactivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).DeactivateUser(ctx, req.(*DeactivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQueryService_GetUserPreviewByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPreviewByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).GetUserPreviewByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQueryService_GetUserPreviewByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).GetUserPreviewByID(ctx, req.(*GetUserPreviewByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQueryService_GetDetailedUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailedUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).GetDetailedUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQueryService_GetDetailedUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).GetDetailedUserByUsername(ctx, req.(*GetDetailedUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQueryService_ServiceDesc is the grpc.ServiceDesc for UserQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserQueryService",
	HandlerType: (*UserQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExistsByUsername",
			Handler:    _UserQueryService_ExistsByUsername_Handler,
		},
		{
			MethodName: "ActivateUser",
			Handler:    _UserQueryService_ActivateUser_Handler,
		},
		{
			MethodName: "DeactivateUser",
			Handler:    _UserQueryService_DeactivateUser_Handler,
		},
		{
			MethodName: "GetUserPreviewByID",
			Handler:    _UserQueryService_GetUserPreviewByID_Handler,
		},
		{
			MethodName: "GetDetailedUserByUsername",
			Handler:    _UserQueryService_GetDetailedUserByUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/query.proto",
}
