// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/user/v1/query.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExistsByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByUsernameRequest) Reset() {
	*x = ExistsByUsernameRequest{}
	mi := &file_proto_user_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByUsernameRequest) ProtoMessage() {}

func (x *ExistsByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByUsernameRequest.ProtoReflect.Descriptor instead.
func (*ExistsByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *ExistsByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ExistsByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByUsernameResponse) Reset() {
	*x = ExistsByUsernameResponse{}
	mi := &file_proto_user_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByUsernameResponse) ProtoMessage() {}

func (x *ExistsByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByUsernameResponse.ProtoReflect.Descriptor instead.
func (*ExistsByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *ExistsByUsernameResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_user_v1_query_proto protoreflect.FileDescriptor

const file_proto_user_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x19proto/user/v1/query.proto\x12\auser.v1\"5\n" +
	"\x17ExistsByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"2\n" +
	"\x18ExistsByUsernameResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2k\n" +
	"\x10UserQueryService\x12W\n" +
	"\x10ExistsByUsername\x12 .user.v1.ExistsByUsernameRequest\x1a!.user.v1.ExistsByUsernameResponseB?Z=github.com/ofm-microseervices/ofm-common/proto/user/v1;userv1b\x06proto3"

var (
	file_proto_user_v1_query_proto_rawDescOnce sync.Once
	file_proto_user_v1_query_proto_rawDescData []byte
)

func file_proto_user_v1_query_proto_rawDescGZIP() []byte {
	file_proto_user_v1_query_proto_rawDescOnce.Do(func() {
		file_proto_user_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_v1_query_proto_rawDesc), len(file_proto_user_v1_query_proto_rawDesc)))
	})
	return file_proto_user_v1_query_proto_rawDescData
}

var file_proto_user_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_v1_query_proto_goTypes = []any{
	(*ExistsByUsernameRequest)(nil),  // 0: user.v1.ExistsByUsernameRequest
	(*ExistsByUsernameResponse)(nil), // 1: user.v1.ExistsByUsernameResponse
}
var file_proto_user_v1_query_proto_depIdxs = []int32{
	0, // 0: user.v1.UserQueryService.ExistsByUsername:input_type -> user.v1.ExistsByUsernameRequest
	1, // 1: user.v1.UserQueryService.ExistsByUsername:output_type -> user.v1.ExistsByUsernameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_v1_query_proto_init() }
func file_proto_user_v1_query_proto_init() {
	if File_proto_user_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_v1_query_proto_rawDesc), len(file_proto_user_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_v1_query_proto_goTypes,
		DependencyIndexes: file_proto_user_v1_query_proto_depIdxs,
		MessageInfos:      file_proto_user_v1_query_proto_msgTypes,
	}.Build()
	File_proto_user_v1_query_proto = out.File
	file_proto_user_v1_query_proto_goTypes = nil
	file_proto_user_v1_query_proto_depIdxs = nil
}
