// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/query.proto

// Package auth.v1 defines the auth ownership queries shared with
// registration-saga-service.

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExistsByEmailRequest asks whether auth-service already owns the supplied
// email address.
type ExistsByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByEmailRequest) Reset() {
	*x = ExistsByEmailRequest{}
	mi := &file_auth_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByEmailRequest) ProtoMessage() {}

func (x *ExistsByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByEmailRequest.ProtoReflect.Descriptor instead.
func (*ExistsByEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *ExistsByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// ExistsByEmailResponse reports whether the email is already owned by
// auth-service.
type ExistsByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByEmailResponse) Reset() {
	*x = ExistsByEmailResponse{}
	mi := &file_auth_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByEmailResponse) ProtoMessage() {}

func (x *ExistsByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByEmailResponse.ProtoReflect.Descriptor instead.
func (*ExistsByEmailResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *ExistsByEmailResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// VerifyRegistrationEmailRequest verifies the pending registration code owned
// by auth-service.
type VerifyRegistrationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRegistrationEmailRequest) Reset() {
	*x = VerifyRegistrationEmailRequest{}
	mi := &file_auth_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRegistrationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRegistrationEmailRequest) ProtoMessage() {}

func (x *VerifyRegistrationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRegistrationEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyRegistrationEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRegistrationEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyRegistrationEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// VerifyRegistrationEmailResponse reports whether the pending auth data is now
// verified.
type VerifyRegistrationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRegistrationEmailResponse) Reset() {
	*x = VerifyRegistrationEmailResponse{}
	mi := &file_auth_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRegistrationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRegistrationEmailResponse) ProtoMessage() {}

func (x *VerifyRegistrationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRegistrationEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyRegistrationEmailResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyRegistrationEmailResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyRegistrationEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyRegistrationEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// IssueRegistrationTokensRequest asks auth-service to create the final login
// tokens after the saga has completed.
type IssueRegistrationTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRegistrationTokensRequest) Reset() {
	*x = IssueRegistrationTokensRequest{}
	mi := &file_auth_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRegistrationTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRegistrationTokensRequest) ProtoMessage() {}

func (x *IssueRegistrationTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRegistrationTokensRequest.ProtoReflect.Descriptor instead.
func (*IssueRegistrationTokensRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *IssueRegistrationTokensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// IssueRegistrationTokensResponse returns the login tokens over the private
// gRPC boundary to api-gateway.
type IssueRegistrationTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRegistrationTokensResponse) Reset() {
	*x = IssueRegistrationTokensResponse{}
	mi := &file_auth_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRegistrationTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRegistrationTokensResponse) ProtoMessage() {}

func (x *IssueRegistrationTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRegistrationTokensResponse.ProtoReflect.Descriptor instead.
func (*IssueRegistrationTokensResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *IssueRegistrationTokensResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueRegistrationTokensResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueRegistrationTokensResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *IssueRegistrationTokensResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *IssueRegistrationTokensResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// DeactivateRegistrationAuthRequest is the compensation command for auth data.
type DeactivateRegistrationAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRegistrationAuthRequest) Reset() {
	*x = DeactivateRegistrationAuthRequest{}
	mi := &file_auth_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRegistrationAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRegistrationAuthRequest) ProtoMessage() {}

func (x *DeactivateRegistrationAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRegistrationAuthRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRegistrationAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateRegistrationAuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeactivateRegistrationAuthResponse reports compensation completion.
type DeactivateRegistrationAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRegistrationAuthResponse) Reset() {
	*x = DeactivateRegistrationAuthResponse{}
	mi := &file_auth_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRegistrationAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRegistrationAuthResponse) ProtoMessage() {}

func (x *DeactivateRegistrationAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRegistrationAuthResponse.ProtoReflect.Descriptor instead.
func (*DeactivateRegistrationAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *DeactivateRegistrationAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeactivateRegistrationAuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_auth_v1_query_proto protoreflect.FileDescriptor

const file_auth_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x13auth/v1/query.proto\x12\aauth.v1\",\n" +
	"\x14ExistsByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"/\n" +
	"\x15ExistsByEmailResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"M\n" +
	"\x1eVerifyRegistrationEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"h\n" +
	"\x1fVerifyRegistrationEmailResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"9\n" +
	"\x1eIssueRegistrationTokensRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc0\x01\n" +
	"\x1fIssueRegistrationTokensResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\"<\n" +
	"!DeactivateRegistrationAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\"DeactivateRegistrationAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xb5\x03\n" +
	"\x10AuthQueryService\x12N\n" +
	"\rExistsByEmail\x12\x1d.auth.v1.ExistsByEmailRequest\x1a\x1e.auth.v1.ExistsByEmailResponse\x12l\n" +
	"\x17VerifyRegistrationEmail\x12'.auth.v1.VerifyRegistrationEmailRequest\x1a(.auth.v1.VerifyRegistrationEmailResponse\x12l\n" +
	"\x17IssueRegistrationTokens\x12'.auth.v1.IssueRegistrationTokensRequest\x1a(.auth.v1.IssueRegistrationTokensResponse\x12u\n" +
	"\x1aDeactivateRegistrationAuth\x12*.auth.v1.DeactivateRegistrationAuthRequest\x1a+.auth.v1.DeactivateRegistrationAuthResponseB?Z=github.com/ofm-microservices/ofm-common/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_query_proto_rawDescOnce sync.Once
	file_auth_v1_query_proto_rawDescData []byte
)

func file_auth_v1_query_proto_rawDescGZIP() []byte {
	file_auth_v1_query_proto_rawDescOnce.Do(func() {
		file_auth_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_query_proto_rawDesc), len(file_auth_v1_query_proto_rawDesc)))
	})
	return file_auth_v1_query_proto_rawDescData
}

var file_auth_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_v1_query_proto_goTypes = []any{
	(*ExistsByEmailRequest)(nil),               // 0: auth.v1.ExistsByEmailRequest
	(*ExistsByEmailResponse)(nil),              // 1: auth.v1.ExistsByEmailResponse
	(*VerifyRegistrationEmailRequest)(nil),     // 2: auth.v1.VerifyRegistrationEmailRequest
	(*VerifyRegistrationEmailResponse)(nil),    // 3: auth.v1.VerifyRegistrationEmailResponse
	(*IssueRegistrationTokensRequest)(nil),     // 4: auth.v1.IssueRegistrationTokensRequest
	(*IssueRegistrationTokensResponse)(nil),    // 5: auth.v1.IssueRegistrationTokensResponse
	(*DeactivateRegistrationAuthRequest)(nil),  // 6: auth.v1.DeactivateRegistrationAuthRequest
	(*DeactivateRegistrationAuthResponse)(nil), // 7: auth.v1.DeactivateRegistrationAuthResponse
}
var file_auth_v1_query_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthQueryService.ExistsByEmail:input_type -> auth.v1.ExistsByEmailRequest
	2, // 1: auth.v1.AuthQueryService.VerifyRegistrationEmail:input_type -> auth.v1.VerifyRegistrationEmailRequest
	4, // 2: auth.v1.AuthQueryService.IssueRegistrationTokens:input_type -> auth.v1.IssueRegistrationTokensRequest
	6, // 3: auth.v1.AuthQueryService.DeactivateRegistrationAuth:input_type -> auth.v1.DeactivateRegistrationAuthRequest
	1, // 4: auth.v1.AuthQueryService.ExistsByEmail:output_type -> auth.v1.ExistsByEmailResponse
	3, // 5: auth.v1.AuthQueryService.VerifyRegistrationEmail:output_type -> auth.v1.VerifyRegistrationEmailResponse
	5, // 6: auth.v1.AuthQueryService.IssueRegistrationTokens:output_type -> auth.v1.IssueRegistrationTokensResponse
	7, // 7: auth.v1.AuthQueryService.DeactivateRegistrationAuth:output_type -> auth.v1.DeactivateRegistrationAuthResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_query_proto_init() }
func file_auth_v1_query_proto_init() {
	if File_auth_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_query_proto_rawDesc), len(file_auth_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_query_proto_goTypes,
		DependencyIndexes: file_auth_v1_query_proto_depIdxs,
		MessageInfos:      file_auth_v1_query_proto_msgTypes,
	}.Build()
	File_auth_v1_query_proto = out.File
	file_auth_v1_query_proto_goTypes = nil
	file_auth_v1_query_proto_depIdxs = nil
}
