// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/session.proto

// Package auth.v1 defines the auth session exchange shared with api-gateway.

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignInRequest submits a username-or-email identifier plus password.
type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_auth_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SignInRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// AuthTokensResponse returns access and refresh tokens for an authenticated
// user.
type AuthTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokensResponse) Reset() {
	*x = AuthTokensResponse{}
	mi := &file_auth_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokensResponse) ProtoMessage() {}

func (x *AuthTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokensResponse.ProtoReflect.Descriptor instead.
func (*AuthTokensResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *AuthTokensResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthTokensResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthTokensResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthTokensResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AuthTokensResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_auth_v1_session_proto protoreflect.FileDescriptor

const file_auth_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/session.proto\x12\aauth.v1\"K\n" +
	"\rSignInRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb3\x01\n" +
	"\x12AuthTokensResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn2S\n" +
	"\x12AuthSessionService\x12=\n" +
	"\x06SignIn\x12\x16.auth.v1.SignInRequest\x1a\x1b.auth.v1.AuthTokensResponseB>Z<github.com/ofm-microservices/ofm-common/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_session_proto_rawDescOnce sync.Once
	file_auth_v1_session_proto_rawDescData []byte
)

func file_auth_v1_session_proto_rawDescGZIP() []byte {
	file_auth_v1_session_proto_rawDescOnce.Do(func() {
		file_auth_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_session_proto_rawDesc), len(file_auth_v1_session_proto_rawDesc)))
	})
	return file_auth_v1_session_proto_rawDescData
}

var file_auth_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_session_proto_goTypes = []any{
	(*SignInRequest)(nil),      // 0: auth.v1.SignInRequest
	(*AuthTokensResponse)(nil), // 1: auth.v1.AuthTokensResponse
}
var file_auth_v1_session_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthSessionService.SignIn:input_type -> auth.v1.SignInRequest
	1, // 1: auth.v1.AuthSessionService.SignIn:output_type -> auth.v1.AuthTokensResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_session_proto_init() }
func file_auth_v1_session_proto_init() {
	if File_auth_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_session_proto_rawDesc), len(file_auth_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_session_proto_goTypes,
		DependencyIndexes: file_auth_v1_session_proto_depIdxs,
		MessageInfos:      file_auth_v1_session_proto_msgTypes,
	}.Build()
	File_auth_v1_session_proto = out.File
	file_auth_v1_session_proto_goTypes = nil
	file_auth_v1_session_proto_depIdxs = nil
}
