// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ordercheckout/v1/ordercheckout.proto

// Package ordercheckout.v1 defines the synchronous checkout wizard contract
// used by api-gateway and order-saga-service.

package ordercheckoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GigId              string                 `protobuf:"bytes,1,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	PackageId          string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	SellerUserId       string                 `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	GigTitle           string                 `protobuf:"bytes,4,opt,name=gig_title,json=gigTitle,proto3" json:"gig_title,omitempty"`
	PackageTitle       string                 `protobuf:"bytes,5,opt,name=package_title,json=packageTitle,proto3" json:"package_title,omitempty"`
	PackageDescription string                 `protobuf:"bytes,6,opt,name=package_description,json=packageDescription,proto3" json:"package_description,omitempty"`
	PriceAmount        int64                  `protobuf:"varint,7,opt,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	PriceCurrency      string                 `protobuf:"bytes,8,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	DeliveryDays       int32                  `protobuf:"varint,9,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	RevisionCount      int32                  `protobuf:"varint,10,opt,name=revision_count,json=revisionCount,proto3" json:"revision_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderSnapshot) Reset() {
	*x = OrderSnapshot{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSnapshot) ProtoMessage() {}

func (x *OrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSnapshot.ProtoReflect.Descriptor instead.
func (*OrderSnapshot) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{0}
}

func (x *OrderSnapshot) GetGigId() string {
	if x != nil {
		return x.GigId
	}
	return ""
}

func (x *OrderSnapshot) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OrderSnapshot) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *OrderSnapshot) GetGigTitle() string {
	if x != nil {
		return x.GigTitle
	}
	return ""
}

func (x *OrderSnapshot) GetPackageTitle() string {
	if x != nil {
		return x.PackageTitle
	}
	return ""
}

func (x *OrderSnapshot) GetPackageDescription() string {
	if x != nil {
		return x.PackageDescription
	}
	return ""
}

func (x *OrderSnapshot) GetPriceAmount() int64 {
	if x != nil {
		return x.PriceAmount
	}
	return 0
}

func (x *OrderSnapshot) GetPriceCurrency() string {
	if x != nil {
		return x.PriceCurrency
	}
	return ""
}

func (x *OrderSnapshot) GetDeliveryDays() int32 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

func (x *OrderSnapshot) GetRevisionCount() int32 {
	if x != nil {
		return x.RevisionCount
	}
	return 0
}

type OrderQuestionOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQuestionOption) Reset() {
	*x = OrderQuestionOption{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuestionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuestionOption) ProtoMessage() {}

func (x *OrderQuestionOption) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuestionOption.ProtoReflect.Descriptor instead.
func (*OrderQuestionOption) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{1}
}

func (x *OrderQuestionOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OrderQuestionOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type OrderQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Options       []*OrderQuestionOption `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQuestion) Reset() {
	*x = OrderQuestion{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuestion) ProtoMessage() {}

func (x *OrderQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuestion.ProtoReflect.Descriptor instead.
func (*OrderQuestion) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{2}
}

func (x *OrderQuestion) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *OrderQuestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OrderQuestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderQuestion) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *OrderQuestion) GetOptions() []*OrderQuestionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OrderQuestion) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type StartOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId          string                 `protobuf:"bytes,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	BuyerEmail           string                 `protobuf:"bytes,2,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	GigId                string                 `protobuf:"bytes,3,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	PackageId            string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId        string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	RealtimeConnectionId string                 `protobuf:"bytes,7,opt,name=realtime_connection_id,json=realtimeConnectionId,proto3" json:"realtime_connection_id,omitempty"`
	RequestedAt          string                 `protobuf:"bytes,8,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartOrderRequest) Reset() {
	*x = StartOrderRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderRequest) ProtoMessage() {}

func (x *StartOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderRequest.ProtoReflect.Descriptor instead.
func (*StartOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{3}
}

func (x *StartOrderRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *StartOrderRequest) GetBuyerEmail() string {
	if x != nil {
		return x.BuyerEmail
	}
	return ""
}

func (x *StartOrderRequest) GetGigId() string {
	if x != nil {
		return x.GigId
	}
	return ""
}

func (x *StartOrderRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *StartOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *StartOrderRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StartOrderRequest) GetRealtimeConnectionId() string {
	if x != nil {
		return x.RealtimeConnectionId
	}
	return ""
}

func (x *StartOrderRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type StartOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Snapshot      *OrderSnapshot         `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Questions     []*OrderQuestion       `protobuf:"bytes,6,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderResponse) Reset() {
	*x = StartOrderResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderResponse) ProtoMessage() {}

func (x *StartOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderResponse.ProtoReflect.Descriptor instead.
func (*StartOrderResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{4}
}

func (x *StartOrderResponse) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *StartOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StartOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartOrderResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *StartOrderResponse) GetSnapshot() *OrderSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *StartOrderResponse) GetQuestions() []*OrderQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type OrderRequirementAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequirementAnswer) Reset() {
	*x = OrderRequirementAnswer{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequirementAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequirementAnswer) ProtoMessage() {}

func (x *OrderRequirementAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequirementAnswer.ProtoReflect.Descriptor instead.
func (*OrderRequirementAnswer) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{5}
}

func (x *OrderRequirementAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *OrderRequirementAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SubmitRequirementsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	OrderId       string                    `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                    `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Answers       []*OrderRequirementAnswer `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	RequestedAt   string                    `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequirementsRequest) Reset() {
	*x = SubmitRequirementsRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequirementsRequest) ProtoMessage() {}

func (x *SubmitRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequirementsRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitRequirementsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitRequirementsRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *SubmitRequirementsRequest) GetAnswers() []*OrderRequirementAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *SubmitRequirementsRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type SubmitRequirementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequirementsResponse) Reset() {
	*x = SubmitRequirementsResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequirementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequirementsResponse) ProtoMessage() {}

func (x *SubmitRequirementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequirementsResponse.ProtoReflect.Descriptor instead.
func (*SubmitRequirementsResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitRequirementsResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitRequirementsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitRequirementsResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type SubmitMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitMessageRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitMessageRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *SubmitMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitMessageRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type SubmitMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageResponse) Reset() {
	*x = SubmitMessageResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageResponse) ProtoMessage() {}

func (x *SubmitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitMessageResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitMessageResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitMessageResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type CreateAttachmentUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentUploadURLRequest) Reset() {
	*x = CreateAttachmentUploadURLRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentUploadURLRequest) ProtoMessage() {}

func (x *CreateAttachmentUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentUploadURLRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAttachmentUploadURLRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateAttachmentUploadURLRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CreateAttachmentUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateAttachmentUploadURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateAttachmentUploadURLRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateAttachmentUploadURLRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type CreateAttachmentUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,2,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentUploadURLResponse) Reset() {
	*x = CreateAttachmentUploadURLResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentUploadURLResponse) ProtoMessage() {}

func (x *CreateAttachmentUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentUploadURLResponse.ProtoReflect.Descriptor instead.
func (*CreateAttachmentUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAttachmentUploadURLResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateAttachmentUploadURLResponse) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *CreateAttachmentUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateAttachmentUploadURLResponse) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type CompleteAttachmentUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,3,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAttachmentUploadRequest) Reset() {
	*x = CompleteAttachmentUploadRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAttachmentUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAttachmentUploadRequest) ProtoMessage() {}

func (x *CompleteAttachmentUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAttachmentUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteAttachmentUploadRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteAttachmentUploadRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CompleteAttachmentUploadRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *CompleteAttachmentUploadRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *CompleteAttachmentUploadRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *CompleteAttachmentUploadRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type CompleteAttachmentUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,2,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAttachmentUploadResponse) Reset() {
	*x = CompleteAttachmentUploadResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAttachmentUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAttachmentUploadResponse) ProtoMessage() {}

func (x *CompleteAttachmentUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAttachmentUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteAttachmentUploadResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteAttachmentUploadResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CompleteAttachmentUploadResponse) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *CompleteAttachmentUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfirmOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderRequest) Reset() {
	*x = ConfirmOrderRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderRequest) ProtoMessage() {}

func (x *ConfirmOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{14}
}

func (x *ConfirmOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmOrderRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *ConfirmOrderRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type ConfirmOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,4,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderResponse) Reset() {
	*x = ConfirmOrderResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderResponse) ProtoMessage() {}

func (x *ConfirmOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderResponse.ProtoReflect.Descriptor instead.
func (*ConfirmOrderResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{15}
}

func (x *ConfirmOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmOrderResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmOrderResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type DeliverOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SellerUserId    string                 `protobuf:"bytes,2,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	DeliveryMessage string                 `protobuf:"bytes,3,opt,name=delivery_message,json=deliveryMessage,proto3" json:"delivery_message,omitempty"`
	AttachmentIds   []string               `protobuf:"bytes,4,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	RequestedAt     string                 `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliverOrderRequest) Reset() {
	*x = DeliverOrderRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOrderRequest) ProtoMessage() {}

func (x *DeliverOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOrderRequest.ProtoReflect.Descriptor instead.
func (*DeliverOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{16}
}

func (x *DeliverOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliverOrderRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *DeliverOrderRequest) GetDeliveryMessage() string {
	if x != nil {
		return x.DeliveryMessage
	}
	return ""
}

func (x *DeliverOrderRequest) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *DeliverOrderRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type DeliverOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverOrderResponse) Reset() {
	*x = DeliverOrderResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOrderResponse) ProtoMessage() {}

func (x *DeliverOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOrderResponse.ProtoReflect.Descriptor instead.
func (*DeliverOrderResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{17}
}

func (x *DeliverOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliverOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliverOrderResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type AcceptDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptDeliveryRequest) Reset() {
	*x = AcceptDeliveryRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDeliveryRequest) ProtoMessage() {}

func (x *AcceptDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDeliveryRequest.ProtoReflect.Descriptor instead.
func (*AcceptDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{18}
}

func (x *AcceptDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AcceptDeliveryRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *AcceptDeliveryRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type AcceptDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptDeliveryResponse) Reset() {
	*x = AcceptDeliveryResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDeliveryResponse) ProtoMessage() {}

func (x *AcceptDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDeliveryResponse.ProtoReflect.Descriptor instead.
func (*AcceptDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{19}
}

func (x *AcceptDeliveryResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AcceptDeliveryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AcceptDeliveryResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type RequestRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRevisionRequest) Reset() {
	*x = RequestRevisionRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRevisionRequest) ProtoMessage() {}

func (x *RequestRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRevisionRequest.ProtoReflect.Descriptor instead.
func (*RequestRevisionRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{20}
}

func (x *RequestRevisionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRevisionRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *RequestRevisionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestRevisionRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type RequestRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRevisionResponse) Reset() {
	*x = RequestRevisionResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRevisionResponse) ProtoMessage() {}

func (x *RequestRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRevisionResponse.ProtoReflect.Descriptor instead.
func (*RequestRevisionResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{21}
}

func (x *RequestRevisionResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRevisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestRevisionResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type OpenDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDisputeRequest) Reset() {
	*x = OpenDisputeRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDisputeRequest) ProtoMessage() {}

func (x *OpenDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDisputeRequest.ProtoReflect.Descriptor instead.
func (*OpenDisputeRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{22}
}

func (x *OpenDisputeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenDisputeRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *OpenDisputeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OpenDisputeRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type OpenDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDisputeResponse) Reset() {
	*x = OpenDisputeResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDisputeResponse) ProtoMessage() {}

func (x *OpenDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDisputeResponse.ProtoReflect.Descriptor instead.
func (*OpenDisputeResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{23}
}

func (x *OpenDisputeResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenDisputeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpenDisputeResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type ResolveDisputeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrderId              string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AdminUserId          string                 `protobuf:"bytes,2,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	FreelancerPercentage int32                  `protobuf:"varint,3,opt,name=freelancer_percentage,json=freelancerPercentage,proto3" json:"freelancer_percentage,omitempty"`
	CustomerPercentage   int32                  `protobuf:"varint,4,opt,name=customer_percentage,json=customerPercentage,proto3" json:"customer_percentage,omitempty"`
	Reason               string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt          string                 `protobuf:"bytes,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveDisputeRequest) Reset() {
	*x = ResolveDisputeRequest{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDisputeRequest) ProtoMessage() {}

func (x *ResolveDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDisputeRequest.ProtoReflect.Descriptor instead.
func (*ResolveDisputeRequest) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{24}
}

func (x *ResolveDisputeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ResolveDisputeRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *ResolveDisputeRequest) GetFreelancerPercentage() int32 {
	if x != nil {
		return x.FreelancerPercentage
	}
	return 0
}

func (x *ResolveDisputeRequest) GetCustomerPercentage() int32 {
	if x != nil {
		return x.CustomerPercentage
	}
	return 0
}

func (x *ResolveDisputeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResolveDisputeRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type ResolveDisputeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep      string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	PaymentReleaseId string                 `protobuf:"bytes,4,opt,name=payment_release_id,json=paymentReleaseId,proto3" json:"payment_release_id,omitempty"`
	StripeTransferId string                 `protobuf:"bytes,5,opt,name=stripe_transfer_id,json=stripeTransferId,proto3" json:"stripe_transfer_id,omitempty"`
	StripeRefundId   string                 `protobuf:"bytes,6,opt,name=stripe_refund_id,json=stripeRefundId,proto3" json:"stripe_refund_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveDisputeResponse) Reset() {
	*x = ResolveDisputeResponse{}
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDisputeResponse) ProtoMessage() {}

func (x *ResolveDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercheckout_v1_ordercheckout_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDisputeResponse.ProtoReflect.Descriptor instead.
func (*ResolveDisputeResponse) Descriptor() ([]byte, []int) {
	return file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP(), []int{25}
}

func (x *ResolveDisputeResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ResolveDisputeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResolveDisputeResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *ResolveDisputeResponse) GetPaymentReleaseId() string {
	if x != nil {
		return x.PaymentReleaseId
	}
	return ""
}

func (x *ResolveDisputeResponse) GetStripeTransferId() string {
	if x != nil {
		return x.StripeTransferId
	}
	return ""
}

func (x *ResolveDisputeResponse) GetStripeRefundId() string {
	if x != nil {
		return x.StripeRefundId
	}
	return ""
}

var File_ordercheckout_v1_ordercheckout_proto protoreflect.FileDescriptor

const file_ordercheckout_v1_ordercheckout_proto_rawDesc = "" +
	"\n" +
	"$ordercheckout/v1/ordercheckout.proto\x12\x10ordercheckout.v1\"\xf4\x02\n" +
	"\rOrderSnapshot\x12\x15\n" +
	"\x06gig_id\x18\x01 \x01(\tR\x05gigId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12$\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tR\fsellerUserId\x12\x1b\n" +
	"\tgig_title\x18\x04 \x01(\tR\bgigTitle\x12#\n" +
	"\rpackage_title\x18\x05 \x01(\tR\fpackageTitle\x12/\n" +
	"\x13package_description\x18\x06 \x01(\tR\x12packageDescription\x12!\n" +
	"\fprice_amount\x18\a \x01(\x03R\vpriceAmount\x12%\n" +
	"\x0eprice_currency\x18\b \x01(\tR\rpriceCurrency\x12#\n" +
	"\rdelivery_days\x18\t \x01(\x05R\fdeliveryDays\x12%\n" +
	"\x0erevision_count\x18\n" +
	" \x01(\x05R\rrevisionCount\"A\n" +
	"\x13OrderQuestionOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xd4\x01\n" +
	"\rOrderQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12?\n" +
	"\aoptions\x18\x05 \x03(\v2%.ordercheckout.v1.OrderQuestionOptionR\aoptions\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"\xb7\x02\n" +
	"\x11StartOrderRequest\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\tR\vbuyerUserId\x12\x1f\n" +
	"\vbuyer_email\x18\x02 \x01(\tR\n" +
	"buyerEmail\x12\x15\n" +
	"\x06gig_id\x18\x03 \x01(\tR\x05gigId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x124\n" +
	"\x16realtime_connection_id\x18\a \x01(\tR\x14realtimeConnectionId\x12!\n" +
	"\frequested_at\x18\b \x01(\tR\vrequestedAt\"\xff\x01\n" +
	"\x12StartOrderResponse\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12;\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x1f.ordercheckout.v1.OrderSnapshotR\bsnapshot\x12=\n" +
	"\tquestions\x18\x06 \x03(\v2\x1f.ordercheckout.v1.OrderQuestionR\tquestions\"O\n" +
	"\x16OrderRequirementAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc1\x01\n" +
	"\x19SubmitRequirementsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12B\n" +
	"\aanswers\x18\x03 \x03(\v2(.ordercheckout.v1.OrderRequirementAnswerR\aanswers\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"r\n" +
	"\x1aSubmitRequirementsResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"\x92\x01\n" +
	"\x14SubmitMessageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"m\n" +
	"\x15SubmitMessageResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"\xdd\x01\n" +
	" CreateAttachmentUploadURLRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12!\n" +
	"\frequested_at\x18\x06 \x01(\tR\vrequestedAt\"\x9d\x01\n" +
	"!CreateAttachmentUploadURLResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rattachment_id\x18\x02 \x01(\tR\fattachmentId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\"\xc3\x01\n" +
	"\x1fCompleteAttachmentUploadRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12#\n" +
	"\rattachment_id\x18\x03 \x01(\tR\fattachmentId\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\x12!\n" +
	"\frequested_at\x18\x05 \x01(\tR\vrequestedAt\"z\n" +
	" CompleteAttachmentUploadResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rattachment_id\x18\x02 \x01(\tR\fattachmentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"w\n" +
	"\x13ConfirmOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"\x8b\x01\n" +
	"\x14ConfirmOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcheckout_url\x18\x04 \x01(\tR\vcheckoutUrl\"\xcb\x01\n" +
	"\x13DeliverOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12$\n" +
	"\x0eseller_user_id\x18\x02 \x01(\tR\fsellerUserId\x12)\n" +
	"\x10delivery_message\x18\x03 \x01(\tR\x0fdeliveryMessage\x12%\n" +
	"\x0eattachment_ids\x18\x04 \x03(\tR\rattachmentIds\x12!\n" +
	"\frequested_at\x18\x05 \x01(\tR\vrequestedAt\"l\n" +
	"\x14DeliverOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"y\n" +
	"\x15AcceptDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"n\n" +
	"\x16AcceptDeliveryResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"\x92\x01\n" +
	"\x16RequestRevisionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"o\n" +
	"\x17RequestRevisionResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"\x8e\x01\n" +
	"\x12OpenDisputeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"k\n" +
	"\x13OpenDisputeResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\"\xf7\x01\n" +
	"\x15ResolveDisputeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\radmin_user_id\x18\x02 \x01(\tR\vadminUserId\x123\n" +
	"\x15freelancer_percentage\x18\x03 \x01(\x05R\x14freelancerPercentage\x12/\n" +
	"\x13customer_percentage\x18\x04 \x01(\x05R\x12customerPercentage\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x06 \x01(\tR\vrequestedAt\"\xf4\x01\n" +
	"\x16ResolveDisputeResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\x12,\n" +
	"\x12payment_release_id\x18\x04 \x01(\tR\x10paymentReleaseId\x12,\n" +
	"\x12stripe_transfer_id\x18\x05 \x01(\tR\x10stripeTransferId\x12(\n" +
	"\x10stripe_refund_id\x18\x06 \x01(\tR\x0estripeRefundId2\x99\t\n" +
	"\x14OrderCheckoutService\x12W\n" +
	"\n" +
	"StartOrder\x12#.ordercheckout.v1.StartOrderRequest\x1a$.ordercheckout.v1.StartOrderResponse\x12o\n" +
	"\x12SubmitRequirements\x12+.ordercheckout.v1.SubmitRequirementsRequest\x1a,.ordercheckout.v1.SubmitRequirementsResponse\x12`\n" +
	"\rSubmitMessage\x12&.ordercheckout.v1.SubmitMessageRequest\x1a'.ordercheckout.v1.SubmitMessageResponse\x12\x84\x01\n" +
	"\x19CreateAttachmentUploadURL\x122.ordercheckout.v1.CreateAttachmentUploadURLRequest\x1a3.ordercheckout.v1.CreateAttachmentUploadURLResponse\x12\x81\x01\n" +
	"\x18CompleteAttachmentUpload\x121.ordercheckout.v1.CompleteAttachmentUploadRequest\x1a2.ordercheckout.v1.CompleteAttachmentUploadResponse\x12]\n" +
	"\fConfirmOrder\x12%.ordercheckout.v1.ConfirmOrderRequest\x1a&.ordercheckout.v1.ConfirmOrderResponse\x12]\n" +
	"\fDeliverOrder\x12%.ordercheckout.v1.DeliverOrderRequest\x1a&.ordercheckout.v1.DeliverOrderResponse\x12c\n" +
	"\x0eAcceptDelivery\x12'.ordercheckout.v1.AcceptDeliveryRequest\x1a(.ordercheckout.v1.AcceptDeliveryResponse\x12f\n" +
	"\x0fRequestRevision\x12(.ordercheckout.v1.RequestRevisionRequest\x1a).ordercheckout.v1.RequestRevisionResponse\x12Z\n" +
	"\vOpenDispute\x12$.ordercheckout.v1.OpenDisputeRequest\x1a%.ordercheckout.v1.OpenDisputeResponse\x12c\n" +
	"\x0eResolveDispute\x12'.ordercheckout.v1.ResolveDisputeRequest\x1a(.ordercheckout.v1.ResolveDisputeResponseBPZNgithub.com/ofm-microservices/ofm-common/proto/ordercheckout/v1;ordercheckoutv1b\x06proto3"

var (
	file_ordercheckout_v1_ordercheckout_proto_rawDescOnce sync.Once
	file_ordercheckout_v1_ordercheckout_proto_rawDescData []byte
)

func file_ordercheckout_v1_ordercheckout_proto_rawDescGZIP() []byte {
	file_ordercheckout_v1_ordercheckout_proto_rawDescOnce.Do(func() {
		file_ordercheckout_v1_ordercheckout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordercheckout_v1_ordercheckout_proto_rawDesc), len(file_ordercheckout_v1_ordercheckout_proto_rawDesc)))
	})
	return file_ordercheckout_v1_ordercheckout_proto_rawDescData
}

var file_ordercheckout_v1_ordercheckout_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_ordercheckout_v1_ordercheckout_proto_goTypes = []any{
	(*OrderSnapshot)(nil),                     // 0: ordercheckout.v1.OrderSnapshot
	(*OrderQuestionOption)(nil),               // 1: ordercheckout.v1.OrderQuestionOption
	(*OrderQuestion)(nil),                     // 2: ordercheckout.v1.OrderQuestion
	(*StartOrderRequest)(nil),                 // 3: ordercheckout.v1.StartOrderRequest
	(*StartOrderResponse)(nil),                // 4: ordercheckout.v1.StartOrderResponse
	(*OrderRequirementAnswer)(nil),            // 5: ordercheckout.v1.OrderRequirementAnswer
	(*SubmitRequirementsRequest)(nil),         // 6: ordercheckout.v1.SubmitRequirementsRequest
	(*SubmitRequirementsResponse)(nil),        // 7: ordercheckout.v1.SubmitRequirementsResponse
	(*SubmitMessageRequest)(nil),              // 8: ordercheckout.v1.SubmitMessageRequest
	(*SubmitMessageResponse)(nil),             // 9: ordercheckout.v1.SubmitMessageResponse
	(*CreateAttachmentUploadURLRequest)(nil),  // 10: ordercheckout.v1.CreateAttachmentUploadURLRequest
	(*CreateAttachmentUploadURLResponse)(nil), // 11: ordercheckout.v1.CreateAttachmentUploadURLResponse
	(*CompleteAttachmentUploadRequest)(nil),   // 12: ordercheckout.v1.CompleteAttachmentUploadRequest
	(*CompleteAttachmentUploadResponse)(nil),  // 13: ordercheckout.v1.CompleteAttachmentUploadResponse
	(*ConfirmOrderRequest)(nil),               // 14: ordercheckout.v1.ConfirmOrderRequest
	(*ConfirmOrderResponse)(nil),              // 15: ordercheckout.v1.ConfirmOrderResponse
	(*DeliverOrderRequest)(nil),               // 16: ordercheckout.v1.DeliverOrderRequest
	(*DeliverOrderResponse)(nil),              // 17: ordercheckout.v1.DeliverOrderResponse
	(*AcceptDeliveryRequest)(nil),             // 18: ordercheckout.v1.AcceptDeliveryRequest
	(*AcceptDeliveryResponse)(nil),            // 19: ordercheckout.v1.AcceptDeliveryResponse
	(*RequestRevisionRequest)(nil),            // 20: ordercheckout.v1.RequestRevisionRequest
	(*RequestRevisionResponse)(nil),           // 21: ordercheckout.v1.RequestRevisionResponse
	(*OpenDisputeRequest)(nil),                // 22: ordercheckout.v1.OpenDisputeRequest
	(*OpenDisputeResponse)(nil),               // 23: ordercheckout.v1.OpenDisputeResponse
	(*ResolveDisputeRequest)(nil),             // 24: ordercheckout.v1.ResolveDisputeRequest
	(*ResolveDisputeResponse)(nil),            // 25: ordercheckout.v1.ResolveDisputeResponse
}
var file_ordercheckout_v1_ordercheckout_proto_depIdxs = []int32{
	1,  // 0: ordercheckout.v1.OrderQuestion.options:type_name -> ordercheckout.v1.OrderQuestionOption
	0,  // 1: ordercheckout.v1.StartOrderResponse.snapshot:type_name -> ordercheckout.v1.OrderSnapshot
	2,  // 2: ordercheckout.v1.StartOrderResponse.questions:type_name -> ordercheckout.v1.OrderQuestion
	5,  // 3: ordercheckout.v1.SubmitRequirementsRequest.answers:type_name -> ordercheckout.v1.OrderRequirementAnswer
	3,  // 4: ordercheckout.v1.OrderCheckoutService.StartOrder:input_type -> ordercheckout.v1.StartOrderRequest
	6,  // 5: ordercheckout.v1.OrderCheckoutService.SubmitRequirements:input_type -> ordercheckout.v1.SubmitRequirementsRequest
	8,  // 6: ordercheckout.v1.OrderCheckoutService.SubmitMessage:input_type -> ordercheckout.v1.SubmitMessageRequest
	10, // 7: ordercheckout.v1.OrderCheckoutService.CreateAttachmentUploadURL:input_type -> ordercheckout.v1.CreateAttachmentUploadURLRequest
	12, // 8: ordercheckout.v1.OrderCheckoutService.CompleteAttachmentUpload:input_type -> ordercheckout.v1.CompleteAttachmentUploadRequest
	14, // 9: ordercheckout.v1.OrderCheckoutService.ConfirmOrder:input_type -> ordercheckout.v1.ConfirmOrderRequest
	16, // 10: ordercheckout.v1.OrderCheckoutService.DeliverOrder:input_type -> ordercheckout.v1.DeliverOrderRequest
	18, // 11: ordercheckout.v1.OrderCheckoutService.AcceptDelivery:input_type -> ordercheckout.v1.AcceptDeliveryRequest
	20, // 12: ordercheckout.v1.OrderCheckoutService.RequestRevision:input_type -> ordercheckout.v1.RequestRevisionRequest
	22, // 13: ordercheckout.v1.OrderCheckoutService.OpenDispute:input_type -> ordercheckout.v1.OpenDisputeRequest
	24, // 14: ordercheckout.v1.OrderCheckoutService.ResolveDispute:input_type -> ordercheckout.v1.ResolveDisputeRequest
	4,  // 15: ordercheckout.v1.OrderCheckoutService.StartOrder:output_type -> ordercheckout.v1.StartOrderResponse
	7,  // 16: ordercheckout.v1.OrderCheckoutService.SubmitRequirements:output_type -> ordercheckout.v1.SubmitRequirementsResponse
	9,  // 17: ordercheckout.v1.OrderCheckoutService.SubmitMessage:output_type -> ordercheckout.v1.SubmitMessageResponse
	11, // 18: ordercheckout.v1.OrderCheckoutService.CreateAttachmentUploadURL:output_type -> ordercheckout.v1.CreateAttachmentUploadURLResponse
	13, // 19: ordercheckout.v1.OrderCheckoutService.CompleteAttachmentUpload:output_type -> ordercheckout.v1.CompleteAttachmentUploadResponse
	15, // 20: ordercheckout.v1.OrderCheckoutService.ConfirmOrder:output_type -> ordercheckout.v1.ConfirmOrderResponse
	17, // 21: ordercheckout.v1.OrderCheckoutService.DeliverOrder:output_type -> ordercheckout.v1.DeliverOrderResponse
	19, // 22: ordercheckout.v1.OrderCheckoutService.AcceptDelivery:output_type -> ordercheckout.v1.AcceptDeliveryResponse
	21, // 23: ordercheckout.v1.OrderCheckoutService.RequestRevision:output_type -> ordercheckout.v1.RequestRevisionResponse
	23, // 24: ordercheckout.v1.OrderCheckoutService.OpenDispute:output_type -> ordercheckout.v1.OpenDisputeResponse
	25, // 25: ordercheckout.v1.OrderCheckoutService.ResolveDispute:output_type -> ordercheckout.v1.ResolveDisputeResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ordercheckout_v1_ordercheckout_proto_init() }
func file_ordercheckout_v1_ordercheckout_proto_init() {
	if File_ordercheckout_v1_ordercheckout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordercheckout_v1_ordercheckout_proto_rawDesc), len(file_ordercheckout_v1_ordercheckout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordercheckout_v1_ordercheckout_proto_goTypes,
		DependencyIndexes: file_ordercheckout_v1_ordercheckout_proto_depIdxs,
		MessageInfos:      file_ordercheckout_v1_ordercheckout_proto_msgTypes,
	}.Build()
	File_ordercheckout_v1_ordercheckout_proto = out.File
	file_ordercheckout_v1_ordercheckout_proto_goTypes = nil
	file_ordercheckout_v1_ordercheckout_proto_depIdxs = nil
}
