// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ordercheckout/v1/ordercheckout.proto

// Package ordercheckout.v1 defines the synchronous checkout wizard contract
// used by api-gateway and order-saga-service.

package ordercheckoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderCheckoutService_StartOrder_FullMethodName                = "/ordercheckout.v1.OrderCheckoutService/StartOrder"
	OrderCheckoutService_SubmitRequirements_FullMethodName        = "/ordercheckout.v1.OrderCheckoutService/SubmitRequirements"
	OrderCheckoutService_SubmitMessage_FullMethodName             = "/ordercheckout.v1.OrderCheckoutService/SubmitMessage"
	OrderCheckoutService_CreateAttachmentUploadURL_FullMethodName = "/ordercheckout.v1.OrderCheckoutService/CreateAttachmentUploadURL"
	OrderCheckoutService_CompleteAttachmentUpload_FullMethodName  = "/ordercheckout.v1.OrderCheckoutService/CompleteAttachmentUpload"
	OrderCheckoutService_ConfirmOrder_FullMethodName              = "/ordercheckout.v1.OrderCheckoutService/ConfirmOrder"
)

// OrderCheckoutServiceClient is the client API for OrderCheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderCheckoutService owns the public order wizard API.
type OrderCheckoutServiceClient interface {
	StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderResponse, error)
	SubmitRequirements(ctx context.Context, in *SubmitRequirementsRequest, opts ...grpc.CallOption) (*SubmitRequirementsResponse, error)
	SubmitMessage(ctx context.Context, in *SubmitMessageRequest, opts ...grpc.CallOption) (*SubmitMessageResponse, error)
	CreateAttachmentUploadURL(ctx context.Context, in *CreateAttachmentUploadURLRequest, opts ...grpc.CallOption) (*CreateAttachmentUploadURLResponse, error)
	CompleteAttachmentUpload(ctx context.Context, in *CompleteAttachmentUploadRequest, opts ...grpc.CallOption) (*CompleteAttachmentUploadResponse, error)
	ConfirmOrder(ctx context.Context, in *ConfirmOrderRequest, opts ...grpc.CallOption) (*ConfirmOrderResponse, error)
}

type orderCheckoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderCheckoutServiceClient(cc grpc.ClientConnInterface) OrderCheckoutServiceClient {
	return &orderCheckoutServiceClient{cc}
}

func (c *orderCheckoutServiceClient) StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOrderResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_StartOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCheckoutServiceClient) SubmitRequirements(ctx context.Context, in *SubmitRequirementsRequest, opts ...grpc.CallOption) (*SubmitRequirementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRequirementsResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_SubmitRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCheckoutServiceClient) SubmitMessage(ctx context.Context, in *SubmitMessageRequest, opts ...grpc.CallOption) (*SubmitMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMessageResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_SubmitMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCheckoutServiceClient) CreateAttachmentUploadURL(ctx context.Context, in *CreateAttachmentUploadURLRequest, opts ...grpc.CallOption) (*CreateAttachmentUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttachmentUploadURLResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_CreateAttachmentUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCheckoutServiceClient) CompleteAttachmentUpload(ctx context.Context, in *CompleteAttachmentUploadRequest, opts ...grpc.CallOption) (*CompleteAttachmentUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAttachmentUploadResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_CompleteAttachmentUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCheckoutServiceClient) ConfirmOrder(ctx context.Context, in *ConfirmOrderRequest, opts ...grpc.CallOption) (*ConfirmOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmOrderResponse)
	err := c.cc.Invoke(ctx, OrderCheckoutService_ConfirmOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderCheckoutServiceServer is the server API for OrderCheckoutService service.
// All implementations should embed UnimplementedOrderCheckoutServiceServer
// for forward compatibility.
//
// OrderCheckoutService owns the public order wizard API.
type OrderCheckoutServiceServer interface {
	StartOrder(context.Context, *StartOrderRequest) (*StartOrderResponse, error)
	SubmitRequirements(context.Context, *SubmitRequirementsRequest) (*SubmitRequirementsResponse, error)
	SubmitMessage(context.Context, *SubmitMessageRequest) (*SubmitMessageResponse, error)
	CreateAttachmentUploadURL(context.Context, *CreateAttachmentUploadURLRequest) (*CreateAttachmentUploadURLResponse, error)
	CompleteAttachmentUpload(context.Context, *CompleteAttachmentUploadRequest) (*CompleteAttachmentUploadResponse, error)
	ConfirmOrder(context.Context, *ConfirmOrderRequest) (*ConfirmOrderResponse, error)
}

// UnimplementedOrderCheckoutServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderCheckoutServiceServer struct{}

func (UnimplementedOrderCheckoutServiceServer) StartOrder(context.Context, *StartOrderRequest) (*StartOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOrder not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) SubmitRequirements(context.Context, *SubmitRequirementsRequest) (*SubmitRequirementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRequirements not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) SubmitMessage(context.Context, *SubmitMessageRequest) (*SubmitMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMessage not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) CreateAttachmentUploadURL(context.Context, *CreateAttachmentUploadURLRequest) (*CreateAttachmentUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAttachmentUploadURL not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) CompleteAttachmentUpload(context.Context, *CompleteAttachmentUploadRequest) (*CompleteAttachmentUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAttachmentUpload not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) ConfirmOrder(context.Context, *ConfirmOrderRequest) (*ConfirmOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmOrder not implemented")
}
func (UnimplementedOrderCheckoutServiceServer) testEmbeddedByValue() {}

// UnsafeOrderCheckoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderCheckoutServiceServer will
// result in compilation errors.
type UnsafeOrderCheckoutServiceServer interface {
	mustEmbedUnimplementedOrderCheckoutServiceServer()
}

func RegisterOrderCheckoutServiceServer(s grpc.ServiceRegistrar, srv OrderCheckoutServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderCheckoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderCheckoutService_ServiceDesc, srv)
}

func _OrderCheckoutService_StartOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).StartOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_StartOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).StartOrder(ctx, req.(*StartOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCheckoutService_SubmitRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).SubmitRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_SubmitRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).SubmitRequirements(ctx, req.(*SubmitRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCheckoutService_SubmitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).SubmitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_SubmitMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).SubmitMessage(ctx, req.(*SubmitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCheckoutService_CreateAttachmentUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttachmentUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).CreateAttachmentUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_CreateAttachmentUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).CreateAttachmentUploadURL(ctx, req.(*CreateAttachmentUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCheckoutService_CompleteAttachmentUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAttachmentUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).CompleteAttachmentUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_CompleteAttachmentUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).CompleteAttachmentUpload(ctx, req.(*CompleteAttachmentUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCheckoutService_ConfirmOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCheckoutServiceServer).ConfirmOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCheckoutService_ConfirmOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCheckoutServiceServer).ConfirmOrder(ctx, req.(*ConfirmOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderCheckoutService_ServiceDesc is the grpc.ServiceDesc for OrderCheckoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderCheckoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ordercheckout.v1.OrderCheckoutService",
	HandlerType: (*OrderCheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOrder",
			Handler:    _OrderCheckoutService_StartOrder_Handler,
		},
		{
			MethodName: "SubmitRequirements",
			Handler:    _OrderCheckoutService_SubmitRequirements_Handler,
		},
		{
			MethodName: "SubmitMessage",
			Handler:    _OrderCheckoutService_SubmitMessage_Handler,
		},
		{
			MethodName: "CreateAttachmentUploadURL",
			Handler:    _OrderCheckoutService_CreateAttachmentUploadURL_Handler,
		},
		{
			MethodName: "CompleteAttachmentUpload",
			Handler:    _OrderCheckoutService_CompleteAttachmentUpload_Handler,
		},
		{
			MethodName: "ConfirmOrder",
			Handler:    _OrderCheckoutService_ConfirmOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordercheckout/v1/ordercheckout.proto",
}
